import 'package:flutter/material.dart';

/* Text title
    Autogenerated by FlutLab FTF Generator
  */
class SelectFacultyTitle extends StatelessWidget {
  final String facultyName;

  const SelectFacultyTitle({super.key, required this.facultyName});
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        facultyName,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: const TextStyle(
          height: 1.2250000635782878,
          fontSize: 12.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w800,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.8400000000000001, */
        ),
      ),
    );
  }
}
