import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';
import 'package:platonic/providers/flat_provider/providers.dart';
import 'package:platonic/screens/create_flat_screen/step1_screen/widgets/widgets.dart';
import 'package:platonic/screens/create_flat_screen/step2_screen/widgets/widgets.dart';

import 'widgets/widgets.dart';

/* Frame step4
    Autogenerated by FlutLab FTF Generator
  */
class Step4Screen extends ConsumerWidget {
  final formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    Future<void> togglePublishFlat() async {
      if (formKey.currentState!.validate()) {
        formKey.currentState!.save();

        // Get all the flat state
        final flatCreateState = ref.read(flatCreateProvider);

        final jsonData = flatCreateState.toJson();

        // Post and create a flat
        await ref
            .read(flatsScrollProvider.notifier)
            .createFlat(flat: flatCreateState);

        //Navigator.pushReplacementNamed(context, '/GeneratedFlatsWidget');
      }
    }

    return Scaffold(
        backgroundColor: Color.fromARGB(255, 27, 26, 29),
        body: SafeArea(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: formKey,
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      NavigateBefore(title: 'Step 4-4'),
                      SizedBox(
                        height: 22.0,
                      ),
                      SizedBox(
                        height: 33.0,
                        child: CreateFlatDetailTitle(
                          title: '''Ads Details''',
                        ),
                      ),
                      SizedBox(
                        height: 18.0,
                      ),
                      SizedBox(
                          height: 48.0, child: CreateFlatDetailTitleInput()),
                      SizedBox(
                        height: 16.0,
                      ),
                      SizedBox(
                        height: 156.0,
                        child: CreateFlatDetailDescriptionInput(),
                      ),
                      SizedBox(
                        height: 22.0,
                      ),
                      SizedBox(
                        height: 23.0,
                        child: CreateFlatDetailImagesTitle(),
                      ),
                      SizedBox(
                        height: 16.0,
                      ),
                      CreateFlatImagesList(),
                      SizedBox(
                        height: 32.0,
                      ),
                      GestureDetector(
                          onTap: togglePublishFlat,
                          child: Container(
                              alignment: Alignment.center,
                              height: 44.0,
                              decoration: BoxDecoration(
                                color: Color.fromARGB(255, 63, 141, 253),
                                borderRadius: BorderRadius.circular(10.0),
                                boxShadow: [
                                  BoxShadow(
                                    color: Color.fromARGB(63, 0, 0, 0),
                                    offset: Offset(0.0, 4.0),
                                    blurRadius: 4.0,
                                  )
                                ],
                              ),
                              child: CreateFlatDetailButtonText(
                                  text: '''Publish'''))),
                    ]),
              ),
            ),
          ),
        ));
  }
}
