import 'package:flutter/material.dart';
import 'package:platonic/widgets/chat/sended_message/SendedMessageText.dart';

/* Component sended_message
    Autogenerated by FlutLab FTF Generator
  */
class SendedMessage extends StatelessWidget {
  const SendedMessage({super.key, required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
        width: 268.0,
        child: Container(
            padding: const EdgeInsets.all(10.0),
            width: 268.0,
            decoration: const BoxDecoration(
              color: Color.fromARGB(255, 33, 185, 252),
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(20.0),
                topRight: Radius.circular(20.0),
                bottomRight: Radius.circular(0.0),
                bottomLeft: Radius.circular(20.0),
              ),
            ),
            child: SendedMessageText(
              text: text,
            )));
  }
}
