import 'package:flutter/material.dart';

/* Text uab_title
    Autogenerated by FlutLab FTF Generator
  */
class HomeUniversityTitle extends StatelessWidget {
  const HomeUniversityTitle({super.key});

  @override
  Widget build(BuildContext context) {
    return const Text(
      '''UAB''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2250000635782878,
        fontSize: 24.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w800,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
