import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/meet_provider/src/providers/providers.dart';
import 'package:platonic/widgets/home/MeetItem.dart';

/* Frame meets_scroll
    Autogenerated by FlutLab FTF Generator
  */
class MeetScroll extends ConsumerWidget {
  const MeetScroll({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final meetsState = ref.watch(meetsScrollProvider);

    return SizedBox(
        height: 130.0,
        child: meetsState.when(
          data: (meets) {
            return ListView.separated(
              scrollDirection: Axis.horizontal,
              itemCount: meets.length,
              separatorBuilder: (context, index) {
                return const SizedBox(
                  width: 10.0,
                );
              },
              itemBuilder: (context, index) {
                return ProviderScope(
                  overrides: [
                    meetScrollProvider.overrideWithValue(meets[index])
                  ],
                  child: const SizedBox(
                      width: 80.0, height: 130.0, child: MeetItem()),
                );
              },
            );
          },
          loading: () => const Center(
            child: CircularProgressIndicator(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          error: (error, stackTrace) {
            return Text(error.toString());
          },
        ));
  }
}
