import 'package:flutter/material.dart';
import 'package:platonic/helpers/mask/mask.dart';

/* Ellipse image
    Autogenerated by FlutLab FTF Generator
  */
class MessageImage extends StatelessWidget {
  final String profileImage;

  const MessageImage({super.key, required this.profileImage});
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 60.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: Mask.fromSVGPath(
                'M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z',
                offset: const Offset(0.0, 0.0),
                child: Image.network(
                  profileImage,
                  color: null,
                  fit: BoxFit.cover,
                  width: 60.0,
                  height: 60.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
            )
          ]),
    );
  }
}
