import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/widgets/home/MessageItem.dart';
import '../../providers/chat_provider/src/providers/providers.dart';

/* Frame messages_scroll
    Autogenerated by FlutLab FTF Generator
  */
class MessagesScroll extends ConsumerWidget {
  const MessagesScroll({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final conversationsState = ref.watch(conversationsScrollProvider);

    return conversationsState.when(
      data: (messages) {
        return Flexible(
          flex: 1,
          child: ListView.separated(
            itemCount: messages.length,
            separatorBuilder: (context, index) {
              return const SizedBox(
                height: 10.0,
              );
            },
            itemBuilder: (context, index) {
              return ProviderScope(
                overrides: [
                  conversationScrollProvider.overrideWithValue(messages[index])
                ],
                child: const SizedBox(
                  width: 358.0,
                  height: 80.0,
                  child: MessageItem(),
                ),
              );
            },
          ),
        );
      },
      loading: () => const Center(
        child: CircularProgressIndicator(
          color: Color.fromARGB(255, 255, 255, 255),
        ),
      ),
      error: (error, stackTrace) {
        return Text(error.toString());
      },
    );
  }
}
