import 'package:flutter/material.dart';
import 'package:platonic/widgets/register_detail/meet_select/MeetSelectChild.dart';
import 'package:platonic/widgets/register_detail/meet_title/MeetTitle.dart';

/* Group university_meet
    Autogenerated by FlutLab FTF Generator
  */
class MeetSelect extends StatelessWidget {
  final String placeholder, title;

  const MeetSelect({Key? key, required this.placeholder, required this.title})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 358.0,
      height: 38.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 116.0,
              height: 16.0,
              child: MeetTitle(
                title: title,
              ),
            ),
            Positioned(
              left: 137.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 221.0,
              height: 38.0,
              child: MeetSelectChild(
                placeholder: placeholder,
              ),
            )
          ]),
    );
  }
}
