import 'package:flutter/material.dart';

/* Text roompreferences
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailTitle extends StatelessWidget {
  final String title;

  const CreateFlatDetailTitle({Key? key, required this.title})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      title,
      textAlign: TextAlign.left,
      style: const TextStyle(
        height: 1.3020000457763672,
        fontSize: 24.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
