import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/domains/flat_repository/src/models/models.dart';
import 'package:platonic/domains/http_repository/models/error_app_model.dart';
import 'package:platonic/providers/error_provider/create_flat/step2_error_provider.dart';
import 'package:platonic/providers/flat_provider/providers.dart';
import 'package:flutter/material.dart';

/* Group fees
    Autogenerated by FlutLab FTF Generator
  */
class RentCostElectricityInput extends ConsumerWidget {
  const RentCostElectricityInput({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final flatCreateState = ref.read(flatCreateProvider);

    void onSaved(String? electricity) {
      ref
          .read(flatCreateProvider.notifier)
          .setElectricity(electricityPrice: int.parse(electricity!));
    }

    return TextFormField(
      initialValue: flatCreateState.electricityPriceInCents !=
              FlatModel.emptyFlat.electricityPriceInCents
          ? (flatCreateState.electricityPriceInCents ~/ 100).toString()
          : null,
      onChanged: onSaved,
      keyboardType: TextInputType.number,
      textInputAction: TextInputAction.next,
      textAlignVertical: TextAlignVertical.center,
      validator: (value) {
        if (value == null || value.isEmpty) {
          ref.read(step2ErrorProvider.notifier).state =
              const ErrorApp(code: 'step2costelectricity');
          return 'Cost of electricity is required';
        }

        int? rent = int.tryParse(value);
        if (rent == null || rent < 0 || rent >= 2000) {
          ref.read(step2ErrorProvider.notifier).state =
              const ErrorApp(code: 'step2electricityvalid');
          return 'Cost of electricity must be an integer between 0 and 1999';
        }

        return null;
      },
      maxLines: 1,
      style: const TextStyle(
          height: 1.1530000141688757,
          fontSize: 14.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255)),
      decoration: InputDecoration(
        hintText: AppLocalizations.of(context)!.step2CostElectricityHintText,
        hintStyle: TextStyle(color: Colors.grey[400]),
        counterText: "",
        errorStyle: const TextStyle(fontSize: 0.01),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 10.0,
        ),
        enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: const BorderSide(
                color: Color.fromARGB(255, 43, 45, 46), width: 1.0)),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10.0),
          borderSide: const BorderSide(
              color: Color.fromARGB(255, 43, 45, 46), width: 1.0),
        ),
        errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: const BorderSide(color: Colors.red, width: 1.0)),
        focusedErrorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: const BorderSide(color: Colors.red, width: 1.0)),
      ),
    );
  }
}
