import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class RoomPreferences extends StatelessWidget {
  final GlobalKey<FormState> formKey;

  const RoomPreferences({Key? key, required this.formKey}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 216.0,
      child: Form(
        key: formKey,
        child: const Column(children: [
          Flexible(
            child: RentPerMonthInput(),
          ),
          SizedBox(
            height: 16.0,
          ),
          Flexible(
            child: RentAdvanceInput(),
          ),
          SizedBox(
            height: 16.0,
          ),
          Flexible(
            child: RentCostElectricityInput(),
          ),
          SizedBox(
            height: 16.0,
          ),
          Flexible(
            child: RentAvailableFromInput(),
          )
        ]),
      ),
    );
  }
}
