import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';
import 'widgets.dart';

/* Group bedrooms
    Autogenerated by FlutLab FTF Generator
  */
class TenantsNumberSelector extends StatelessWidget {
  const TenantsNumberSelector({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 70.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        SizedBox(
          height: 26.0,
          child: CreateFlatDetailSubtitle(
            subtitle: AppLocalizations.of(context)!.step2RoomTenantsSubtitle,
          ),
        ),
        const SizedBox(
          height: 14.0,
        ),
        const SizedBox(
          height: 30.0,
          child: TenantsNumberRow(),
        )
      ]),
    );
  }
}
