import 'package:flutter/material.dart';

import 'widgets.dart';

/* Frame bedrooms
    Autogenerated by FlutLab FTF Generator
  */
class TenantsNumberRow extends StatelessWidget {
  final List<int> numbers = [0, 1, 2, 3, 4];

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 30.0,
      child: Row(
        children: numbers
            .map((number) => Padding(
                padding: EdgeInsets.only(
                    left: number == 0 ? 0.0 : 16.0,
                    right: number == numbers.length - 1 ? 16.0 : 0.0),
                child: SizedBox(
                  width: 40.0,
                  height: 30.0,
                  child: TenantsNumberOption(
                    number: number == numbers.length - 1
                        ? '$number+'
                        : '${number + 1}',
                  ),
                )))
            .toList(),
      ),
    );
  }
}
