import 'package:flutter/material.dart';

/* Text num
    Autogenerated by FlutLab FTF Generator
  */
class TenantsNumberOptionText extends StatelessWidget {
  final String number;

  const TenantsNumberOptionText({Key? key, required this.number})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      number,
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: const TextStyle(
        height: 1.3020000457763672,
        fontSize: 12.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
