import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/flat_provider/providers.dart';
import 'widgets.dart';

/* Group num1
    Autogenerated by FlutLab FTF Generator
  */
class TenantsNumberOption extends ConsumerWidget {
  final String number;

  const TenantsNumberOption({Key? key, required this.number}) : super(key: key);
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final flatCreateState = ref.watch(flatCreateProvider);

    void toggleNumberTenants() {
      ref.read(flatCreateProvider.notifier).state =
          flatCreateState.copyWith(tenantsNumber: number);
    }

    return GestureDetector(
      onTap: toggleNumberTenants,
      child: AnimatedContainer(
          duration: const Duration(milliseconds: 300),
          alignment: Alignment.center,
          width: 40.0,
          height: 30.0,
          decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(10.0),
              color: flatCreateState.tenantsNumber == number
                  ? const Color.fromARGB(255, 63, 141, 253)
                  : null,
              border: flatCreateState.tenantsNumber == number
                  ? Border.all(
                      width: 1.0,
                      color: const Color.fromARGB(255, 63, 141, 253))
                  : Border.all(
                      width: 1.0,
                      color: const Color.fromARGB(255, 43, 45, 46))),
          child: TenantsNumberOptionText(number: number)),
    );
  }
}
