import 'package:flutter/material.dart';

/* Text university_title
    Autogenerated by FlutLab FTF Generator
  */
class UniversityTitle extends StatelessWidget {
  const UniversityTitle(
      {super.key,
      required this.universityName,
      required this.universitySimpleName});

  final String universityName, universitySimpleName;

  @override
  Widget build(BuildContext context) {
    return Text(
      '$universityName (${universitySimpleName.toUpperCase()})',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: const TextStyle(
        height: 1.1530000141688757,
        fontSize: 14.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
