import 'package:flutter/material.dart';
import 'package:platonic/helpers/transform/transform.dart';

/* Ellipse Ellipse 12
    Autogenerated by FlutLab FTF Generator
  */
class MatchSmallFavouriteContainer extends StatelessWidget {
  const MatchSmallFavouriteContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 0.87,
        b: -0.50,
        c: 0.50,
        d: 0.87,
        child: Container(
            width: 18.0,
            height: 18.0,
            decoration: const BoxDecoration(
              shape: BoxShape.circle,
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [
                  Color(0xFFFF87B9),
                  Color(0xFFFF5A8D),
                  Color(0xFFCFB4FF),
                ],
                stops: [0.1, 0.5, 0.9],
              ),
            )));
  }
}
