import 'package:flutter/material.dart';
import 'package:platonic/screens/register_detail_screen/widgets/widgets.dart';

/* Group sex_switch
    Autogenerated by FlutLab FTF Generator
  */
class PersonalSwitch extends StatelessWidget {
  const PersonalSwitch({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      height: 38.0,
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        SizedBox(
          width: 50.0,
          height: 38.0,
          child: PersonalTitle(
            title: '''Sex''',
          ),
        ),
        SizedBox(
          width: 258.0,
          height: 38.0,
          child: PersonalMeetSwitch(),
        )
      ]),
    );
  }
}
