import 'package:platonic/screens/register_detail_screen/widgets/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';

/* Group sex_switch
    Autogenerated by FlutLab FTF Generator
  */
class PersonalSwitch extends StatelessWidget {
  const PersonalSwitch({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 38.0,
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        SizedBox(
          width: 50.0,
          height: 38.0,
          child: PersonalTitle(
            title:
                AppLocalizations.of(context)!.registerDetailPersonalSwitchTitle,
          ),
        ),
        const SizedBox(
          width: 258.0,
          height: 38.0,
          child: PersonalMeetSwitch(),
        )
      ]),
    );
  }
}
