import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/domains/university_repository/university_repository.dart';
import 'package:platonic/providers/register_detail_provider/register_detail_provider.dart';
import 'package:platonic/screens/register_detail_screen/widgets/widgets.dart';

/* Group meet switch
    Autogenerated by FlutLab FTF Generator
  */
class PersonalMeetSwitch extends ConsumerWidget {
  const PersonalMeetSwitch({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    EdgeInsets containerMargin =
        ref.read(registerDetailProvider).sex == Sex.male
            ? const EdgeInsets.only(right: 132.0, top: 2.0)
            : const EdgeInsets.only(top: 2.0, left: 132.0);
    return GestureDetector(
      onTap: () => ref.read(registerDetailProvider.notifier).state = ref
          .read(registerDetailProvider)
          .copyWith(
              sex: ref.read(registerDetailProvider).sex == Sex.male
                  ? Sex.female
                  : Sex.male),
      child: Container(
        width: 258.0,
        height: 38.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              const Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 38.0,
                child: PersonalMeetContainer(),
              ),
              AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                margin: containerMargin,
                width: 130.0,
                height: 34.0,
                child: const PersonalBlueContainer(),
              ),
              Positioned(
                left: 132.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 43.0,
                child: PersonalMeetWoman(),
              ),
              const Positioned(
                left: 2.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 39.0,
                child: PersonalMeetMan(),
              )
            ]),
      ),
    );
  }
}
