import 'package:flutter/material.dart';

/* Text minimumstay
    Autogenerated by FlutLab FTF Generator
  */
class PreferencesSliderMinimumTitle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''Minimum stay''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.3020000457763672,
          fontSize: 16.0,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
