import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';

/* Text nominimum
    Autogenerated by FlutLab FTF Generator
  */
class PreferencesSliderNoMinimumTitle extends StatelessWidget {
  const PreferencesSliderNoMinimumTitle({super.key});

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        AppLocalizations.of(context)!.step2SliderMinText,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: const TextStyle(
          height: 1.3020000457763672,
          fontSize: 8.0,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 130, 130, 132),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
