import 'package:flutter/material.dart';

/* Rectangle Rectangle 18
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailImage extends StatelessWidget {
  final String image;

  const CreateFlatDetailImage({Key? key, required this.image})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 95,
      decoration: BoxDecoration(
        image: DecorationImage(
            image: NetworkImage(
              image,
            ),
            fit: BoxFit.cover),
        borderRadius: BorderRadius.circular(5.0),
      ),
    );
  }
}
