import 'package:flutter/material.dart';

import 'widgets.dart';

/* Frame add
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailImageAdd extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: 48.0,
      height: 48.0,
      child: CreateFlatDetailImageAddIcon(),
    );
  }
}
