import 'package:flutter/material.dart';

/* Text minimumstay
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailImagesTitle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RichText(
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        text: const TextSpan(
          style: TextStyle(
            height: 1.3020000457763672,
            fontSize: 16.0,
            fontFamily: 'DM Sans',
            fontWeight: FontWeight.w400,
            color: Color.fromARGB(255, 255, 255, 255),

            /* letterSpacing: 0.0, */
          ),
          children: [
            TextSpan(
              text: '''Property Images ''',
            ),
            TextSpan(
              text: ''' ''',
              style: TextStyle(
                color: Color.fromARGB(255, 255, 0, 0),

                /* letterSpacing: null, */
              ),
            ),
            TextSpan(
              text: '''(Max 20 photos)''',
              style: TextStyle(
                color: Color.fromARGB(255, 130, 130, 132),

                /* letterSpacing: null, */
              ),
            )
          ],
        ));
  }
}
