import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailImageAddIcon extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 28.0,
      height: 28.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M12.5 28L12.5 15.5L0 15.5L0 12.5L12.5 12.5L12.5 0L15.5 0L15.5 12.5L28 12.5L28 15.5L15.5 15.5L15.5 28L12.5 28Z')
          ..color = Color.fromARGB(255, 63, 141, 253),
      ]),
    );
  }
}
