import 'package:flutter/material.dart';
import 'package:platonic/helpers/transform/transform.dart';
import 'package:platonic/widgets/register_detail/personal_title/PersonalTitleText.dart';

/* Instance personal_title
    Autogenerated by FlutLab FTF Generator
  */
class PersonalTitle extends StatelessWidget {
  final String title;

  const PersonalTitle({Key? key, required this.title}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 79.0,
      height: 38.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0632911392405062;

                final double height = constraints.maxHeight * 1.131578947368421;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: PersonalTitleText(
                          title: title,
                        ),
                      ))
                ]);
              }),
            )
          ]),
    );
  }
}
