import 'package:flutter/material.dart';
import 'package:platonic/widgets/register_detail/meet_switch/MeetBlueContainer.dart';
import 'package:platonic/widgets/register_detail/meet_switch/MeetSwitchContainer.dart';
import 'package:platonic/widgets/register_detail/meet_switch/MeetMan.dart';
import 'package:platonic/widgets/register_detail/meet_switch/MeetWoman.dart';

/* Group meet switch
    Autogenerated by FlutLab FTF Generator
  */
class MeetSwitch extends StatefulWidget {
  const MeetSwitch({super.key});

  @override
  State<MeetSwitch> createState() => _MeetSwitchState();
}

class _MeetSwitchState extends State<MeetSwitch> {
  bool _isManSelected = true;

  void _toggleSelection() {
    setState(() {
      _isManSelected = !_isManSelected;
    });
  }

  @override
  Widget build(BuildContext context) {
    EdgeInsets _containerMargin = _isManSelected
        ? EdgeInsets.only(right: 112.0, top: 2.0)
        : EdgeInsets.only(top: 2.0, left: 112.0);
    return GestureDetector(
      onTap: _toggleSelection,
      child: Container(
        width: 221.0,
        height: 32.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 32.0,
                child: MeetSwitchContainer(),
              ),
              AnimatedContainer(
                duration: Duration(milliseconds: 200),
                margin: _containerMargin,
                width: 112.0,
                height: 30.0,
                child: MeetBlueContainer(),
              ),
              Positioned(
                left: 113.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 37.0,
                child: MeetWoman(),
              ),
              Positioned(
                left: 1.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 35.0,
                child: MeetMan(),
              )
            ]),
      ),
    );
  }
}
