import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/register_detail_provider/register_detail_provider.dart';

/* Instance personal_input
    Autogenerated by FlutLab FTF Generator
  */
class PersonalAgeInput extends ConsumerWidget {
  const PersonalAgeInput({super.key});

  String? validateAge(String? value) {
    if (value == null || value.isEmpty) {
      return 'Age is required';
    }
    if (value.length > 2) {
      return 'Age must be less than 100';
    }
    final age = int.tryParse(value);
    if (age == null) {
      return 'Age must be a number';
    }
    return null;
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return TextFormField(
      onSaved: (newValue) => ref.read(registerDetailProvider.notifier).state =
          ref
              .watch(registerDetailProvider)
              .copyWith(age: newValue == null ? null : int.parse(newValue)),
      validator: validateAge,
      keyboardType: TextInputType.number,
      textInputAction: TextInputAction.done,
      textAlignVertical: TextAlignVertical.center,
      maxLength: 2,
      maxLines: null,
      style: const TextStyle(
          height: 1.1530000141688757,
          fontSize: 14.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255)),
      decoration: InputDecoration(
        hintText: '''Your age''',
        hintStyle: TextStyle(color: Colors.grey[400]),
        counterText: "",
        errorStyle: const TextStyle(fontSize: 0.01),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 10.0,
        ),
        enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: const BorderSide(
                color: Color.fromARGB(255, 43, 45, 46), width: 1.0)),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10.0),
          borderSide: const BorderSide(
              color: Color.fromARGB(255, 43, 45, 46), width: 1.0),
        ),
        errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: const BorderSide(color: Colors.red, width: 1.0)),
        focusedErrorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: const BorderSide(color: Colors.red, width: 1.0)),
      ),
    );
  }
}
