import 'package:flutter/material.dart';

/* Text description
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailDescription extends StatelessWidget {
  final String description;

  const CreateFlatDetailDescription({Key? key, required this.description})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      description,
      textAlign: TextAlign.justify,
      softWrap: true,
      style: TextStyle(
        height: 1.3020000457763672,
        fontSize: 14.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
