import 'package:flutter/material.dart';
import 'widgets.dart';

/* Group direction
    Autogenerated by FlutLab FTF Generator
  */
class DetailLocation extends StatelessWidget {
  final String state, city, name;

  const DetailLocation(
      {Key? key, required this.state, required this.city, required this.name})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 17.0,
      child: Row(children: [
        DetailLocationIconContainer(),
        const SizedBox(
          width: 4.0,
        ),
        DetailLocationTitle(
          city: city,
          name: name,
          state: state,
        ),
      ]),
    );
  }
}
