import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame comodities
    Autogenerated by FlutLab FTF Generator
  */
class DetailComodities extends StatelessWidget {
  final String bedroom, bathroom;
  final int built, floor;

  const DetailComodities(
      {Key? key,
      required this.bedroom,
      required this.bathroom,
      required this.built,
      required this.floor})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 42.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        SizedBox(
          height: 16.0,
          child: DetailAmenities(
            bathroom: bathroom,
            bedroom: bedroom,
          ),
        ),
        const SizedBox(
          height: 10.0,
        ),
        SizedBox(
          height: 16.0,
          child: DetailProperty(
            built: built,
            floor: floor,
          ),
        )
      ]),
    );
  }
}
