import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame square
    Autogenerated by FlutLab FTF Generator
  */
class DetailPropertyBuiltIconContainer extends StatelessWidget {
  const DetailPropertyBuiltIconContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      width: 15.0,
      height: 15.0,
      child: DetailPropertyBuiltIcon(),
    );
  }
}
