import 'package:flutter/material.dart';
import 'package:platonic/domains/flat_repository/src/models/models.dart';
import 'package:platonic/screens/features_list_screen/widgets/features_list_item.dart';
import 'widgets.dart';

/* Frame facilities
    Autogenerated by FlutLab FTF Generator
  */
class DetailFeatures extends StatelessWidget {
  final List<FeatureModel> features;

  const DetailFeatures({Key? key, required this.features}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 67.0,
      child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
        for (final feature in features.take(4))
          Expanded(
              child: SizedBox(
                  height: 67.0,
                  child: FeaturesListItem(
                    featureModel: feature,
                  ))),
      ]),
    );
  }
}
