import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame bedicon
    Autogenerated by FlutLab FTF Generator
  */
class DetailAmenitiesBedroomIconContainer extends StatelessWidget {
  const DetailAmenitiesBedroomIconContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: 15.0,
      height: 15.0,
      child: const DetailAmenitiesBedroomIcon(),
    );
  }
}
