import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame bathroom
    Autogenerated by FlutLab FTF Generator
  */
class DetailAmenitiesBathroomIconContainer extends StatelessWidget {
  const DetailAmenitiesBathroomIconContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      width: 15.0,
      height: 15.0,
      child: DetailAmenitiesBathroomIcon(),
    );
  }
}
