import 'package:flutter/material.dart';
import 'widgets.dart';

/* Group book
    Autogenerated by FlutLab FTF Generator
  */
class DetailIconContainer extends StatelessWidget {
  final Widget child;

  const DetailIconContainer({Key? key, required this.child}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
        alignment: Alignment.center,
        width: 35.0,
        height: 35.0,
        decoration: BoxDecoration(
          color: Color.fromARGB(255, 43, 45, 46),
          borderRadius: BorderRadius.circular(5.0),
        ),
        child: child);
  }
}
