import 'package:flutter/material.dart';

/* Line rentline
    Autogenerated by FlutLab FTF Generator
  */
class DetailPrincipalInterestLine extends StatelessWidget {
  const DetailPrincipalInterestLine({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 5.0,
      decoration: BoxDecoration(
          color: const Color.fromARGB(255, 62, 231, 255),
          borderRadius: BorderRadius.circular(5.0)),
    );
  }
}
