import 'package:flutter/material.dart';

/* Text directiontitle
    Autogenerated by FlutLab FTF Generator
  */
class DetailLocationTitle extends StatelessWidget {
  final String city, name, state;

  const DetailLocationTitle(
      {Key? key, required this.city, required this.name, required this.state})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      '$name, $city, $state',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3020000457763672,
        fontSize: 12.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 245, 245, 245),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
