import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class DetailEditIcon extends StatelessWidget {
  const DetailEditIcon({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 15.270833969116211,
      height: 15.270833969116211,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.25 14.0208L2.16667 14.0208L11.3958 4.79167L10.4792 3.875L1.25 13.1042L1.25 14.0208ZM14.0417 3.89583L11.375 1.22917L12.25 0.354167C12.4861 0.118056 12.7778 0 13.125 0C13.4722 0 13.7639 0.118056 14 0.354167L14.9167 1.27083C15.1528 1.50694 15.2708 1.79861 15.2708 2.14583C15.2708 2.49306 15.1528 2.78472 14.9167 3.02083L14.0417 3.89583ZM13.1667 4.77083L2.66667 15.2708L0 15.2708L0 12.6042L10.5 2.10417L13.1667 4.77083ZM10.9375 4.33333L10.4792 3.875L11.3958 4.79167L10.9375 4.33333Z')
          ..color = const Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
