import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';
import 'widgets.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class DetailDeleteIcon extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.333333015441895,
      height: 15.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.10417 15C1.76042 15 1.46615 14.8776 1.22135 14.6328C0.976562 14.388 0.854167 14.0938 0.854167 13.75L0.854167 1.875L0 1.875L0 0.625L3.91667 0.625L3.91667 0L9.41667 0L9.41667 0.625L13.3333 0.625L13.3333 1.875L12.4792 1.875L12.4792 13.75C12.4792 14.0833 12.3542 14.375 12.1042 14.625C11.8542 14.875 11.5625 15 11.2292 15L2.10417 15ZM11.2292 1.875L2.10417 1.875L2.10417 13.75L11.2292 13.75L11.2292 1.875ZM4.3125 11.9583L5.5625 11.9583L5.5625 3.64583L4.3125 3.64583L4.3125 11.9583ZM7.77083 11.9583L9.02083 11.9583L9.02083 3.64583L7.77083 3.64583L7.77083 11.9583Z')
          ..color = Color.fromARGB(255, 255, 76, 0),
      ]),
    );
  }
}
