import 'package:flutter/material.dart';

/* Text By Train to UAB 10 minutes
    Autogenerated by FlutLab FTF Generator
  */
class DetailTransportationTitle extends StatelessWidget {
  final String title;

  const DetailTransportationTitle({Key? key, required this.title})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      title,
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: const TextStyle(
        height: 1.3020000457763672,
        fontSize: 16.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
