import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame firstrow
    Autogenerated by FlutLab FTF Generator
  */
class DetailAmenities extends StatelessWidget {
  final String bedroom, bathroom;

  const DetailAmenities(
      {Key? key, required this.bedroom, required this.bathroom})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 230.0,
      height: 16.0,
      child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [
        SizedBox(
          width: 100.0,
          height: 16.0,
          child: DetailAmenitiesBedroom(
            bedroom: bedroom,
          ),
        ),
        const SizedBox(
          width: 30.0,
        ),
        SizedBox(
            width: 100.0,
            height: 16.0,
            child: DetailAmenitiesBathroom(
              bathroom: bathroom,
            ))
      ]),
    );
  }
}
