import 'package:flutter/material.dart';

/* Line electricitycost
    Autogenerated by FlutLab FTF Generator
  */
class DetailPrincipalElectricityLine extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 5.0,
      decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(5.0),
          color: Color.fromARGB(255, 249, 255, 0)),
    );
  }
}
