import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame secondrow
    Autogenerated by FlutLab FTF Generator
  */
class DetailProperty extends StatelessWidget {
  final int built, floor;

  const DetailProperty({Key? key, required this.built, required this.floor})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 230.0,
      height: 16.0,
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        SizedBox(
          width: 100.0,
          height: 16.0,
          child: DetailPropertyBuilt(
            built: built,
          ),
        ),
        const SizedBox(
          width: 30.0,
        ),
        SizedBox(
          width: 100.0,
          height: 16.0,
          child: DetailPropertyFloor(
            floor: floor,
          ),
        )
      ]),
    );
  }
}
