import 'package:flutter/material.dart';
import 'widgets.dart';

/* Group bathroom
    Autogenerated by FlutLab FTF Generator
  */
class DetailAmenitiesBathroom extends StatelessWidget {
  final String bathroom;

  const DetailAmenitiesBathroom({Key? key, required this.bathroom})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 100.0,
      height: 16.0,
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        SizedBox(
          width: 15.0,
          height: 15.0,
          child: DetailAmenitiesBathroomIconContainer(),
        ),
        SizedBox(
          width: 4.0,
        ),
        DetailAmenitiesBathroomTitle(
          bathroom: bathroom,
        ),
      ]),
    );
  }
}
