import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame floor
    Autogenerated by FlutLab FTF Generator
  */
class DetailPropertyFloorIconContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.0,
      height: 15.0,
      child: DetailPropertyFloorIcon(),
    );
  }
}
