import 'package:flutter/material.dart';
import 'package:platonic/helpers/mask/mask.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class MatchProfileImage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 140.0,
      height: 140.0,
      decoration: BoxDecoration(shape: BoxShape.circle),
      child: Mask.fromSVGPath(
        'M140 70C140 108.66 108.66 140 70 140C31.3401 140 0 108.66 0 70C0 31.3401 31.3401 0 70 0C108.66 0 140 31.3401 140 70Z',
        child: Image.asset(
          "assets/images/ee156dfe98c5469abbb56c7cb5ad5d3aa21a3e1f.png",
          color: null,
          fit: BoxFit.cover,
          width: 140.0,
          height: 140.0,
          colorBlendMode: BlendMode.dstATop,
        ),
        offset: Offset(0.0, 0.0),
      ),
    );
  }
}
