import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/constants/constants.dart';
import 'package:platonic/helpers/mask/mask.dart';
import 'package:platonic/providers/shared_preferences_provider/providers.dart';
import 'package:platonic/providers/user_provider/providers.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class MatchProfileImage extends ConsumerWidget {
  const MatchProfileImage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final userState = ref.watch(appUserProvider);

    return Container(
      width: 140.0,
      height: 140.0,
      decoration: const BoxDecoration(shape: BoxShape.circle),
      child: Mask.fromSVGPath(
        'M140 70C140 108.66 108.66 140 70 140C31.3401 140 0 108.66 0 70C0 31.3401 31.3401 0 70 0C108.66 0 140 31.3401 140 70Z',
        offset: const Offset(0.0, 0.0),
        child: userState.profileImage != null
            ? Image.network(userState.profileImage!,
                fit: BoxFit.cover,
                width: 140.0,
                height: 140.0,
                colorBlendMode: BlendMode.dstATop,
                headers: {
                    'Authorization':
                        'Bearer ${ref.read(sharedPreferencesProvider).getString(FIREBASE_TOKEN_ID_KEY) ?? ''}'
                  })
            : Image.asset(
                'assets/images/default_avatar.jpg',
                fit: BoxFit.cover,
                width: 140.0,
                height: 140.0,
                colorBlendMode: BlendMode.dstATop,
              ),
      ),
    );
  }
}
