import 'package:flutter/material.dart';
import 'package:platonic/widgets/match/users_images/big_favourite/MatchBigFavouriteContainer.dart';
import 'package:platonic/widgets/match/users_images/big_favourite/MatchBigFavouriteIconContainer.dart';

/* Group big_favourite
    Autogenerated by FlutLab FTF Generator
  */
class MatchBigFavourite extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 32.0,
      height: 32.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 32.0,
              height: 32.0,
              child: MatchBigFavouriteContainer(),
            ),
            Positioned(
              left: 6.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: MatchBigFavouriteIconContainer(),
            )
          ]),
    );
  }
}
