import 'package:flutter/material.dart';

/* Ellipse background_selector
    Autogenerated by FlutLab FTF Generator
  */
class BackgroundSelector extends StatelessWidget {
  final Gradient gradient;

  const BackgroundSelector({super.key, required this.gradient});
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 31.0,
      height: 31.0,
      decoration: BoxDecoration(
          shape: BoxShape.circle,
          border: Border.all(
            width: 2.0,
            color: Color.fromARGB(255, 255, 255, 255),
          ),
          gradient: gradient),
    );
  }
}
