import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';

/* Text bathroomtitle
    Autogenerated by FlutLab FTF Generator
  */
class FlatItemBathroomTitle extends StatelessWidget {
  const FlatItemBathroomTitle({super.key, required this.bathroom});

  final String bathroom;

  @override
  Widget build(BuildContext context) {
    return Text(
      AppLocalizations.of(context)!.flatHomeBathroom(bathroom),
      overflow: TextOverflow.ellipsis,
      textAlign: TextAlign.left,
      style: const TextStyle(
        height: 1.3020000457763672,
        fontSize: 12.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 245, 245, 245),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
