import 'package:flutter/material.dart';
import 'widgets.dart';

/* Text meet_description
    Autogenerated by FlutLab FTF Generator
  */
class AmenityDisclaimerText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''If you share a flat with students from other universities, adding them to the flat will also be published in their university and only you will keep the permissions''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.152999997138977,
        fontSize: 16.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 130, 130, 132),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
