import 'package:flutter/material.dart';
import 'package:platonic/screens/create_flat_screen/step2_screen/widgets/widgets.dart';
import 'package:platonic/screens/create_flat_screen/step3_screen/widgets/widgets.dart';
import 'widgets.dart';

/* Group bedrooms
    Autogenerated by FlutLab FTF Generator
  */
class BedroomNumberSelector extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 70.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        SizedBox(
          height: 26.0,
          child: CreateFlatDetailSubtitle(
            subtitle: '''Bedrooms''',
          ),
        ),
        SizedBox(
          height: 14.0,
        ),
        SizedBox(
          height: 30.0,
          child: AmenityNumberRow(
            bedroom: true,
          ),
        )
      ]),
    );
  }
}
