import 'package:flutter/material.dart';
import 'package:platonic/domains/flat_repository/src/models/models.dart';

import 'widgets.dart';

/* Group fees
    Autogenerated by FlutLab FTF Generator
  */
class FeaturesSelect extends StatelessWidget {
  final List<FeatureModel> features;

  const FeaturesSelect({Key? key, required this.features}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    void toggleSelectFeatures() {
      Navigator.pushNamed(context, '/FeaturesCreateScreen');
    }

    return GestureDetector(
      onTap: toggleSelectFeatures,
      child: Container(
        alignment: Alignment.centerLeft,
        padding: const EdgeInsets.symmetric(horizontal: 14.0),
        height: 42.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
          border: Border.all(
            width: 1.0,
            color: const Color.fromARGB(255, 43, 45, 46),
          ),
        ),
        child: FeaturesSelectText(
          features: features,
        ),
      ),
    );
  }
}
