import 'package:flutter/material.dart';
import 'story_add.dart';

/* Frame story_item2
    Autogenerated by FlutLab FTF Generator
  */
class StoryItemEmpty extends StatelessWidget {
  const StoryItemEmpty({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: 100.0,
      height: 135.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
        border: const Border.fromBorderSide(
          BorderSide(
            color: Color.fromARGB(255, 63, 141, 253),
            width: 1.0,
            style: BorderStyle.solid,
          ),
        ),
      ),
      child: const SizedBox(width: 48.0, height: 48.0, child: StoryAdd()),
    );
  }
}
