import 'package:flutter/material.dart';

/* Rectangle story_background
    Autogenerated by FlutLab FTF Generator
  */
class StoryEmptyBackground extends StatelessWidget {
  const StoryEmptyBackground({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100.0,
      height: 135.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
        border: const Border.fromBorderSide(
          BorderSide(
            color: Color.fromARGB(255, 63, 141, 253),
            width: 1.0,
            style: BorderStyle.solid,
          ),
        ),
      ),
    );
  }
}
