import 'package:flutter/material.dart';

/* Text name_title
    Autogenerated by FlutLab FTF Generator
  */
class NameTitle extends StatelessWidget {
  const NameTitle({super.key, required this.name});

  final String name;

  @override
  Widget build(BuildContext context) {
    return Text(
      name,
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: const TextStyle(
        height: 1.225000023841858,
        fontSize: 16.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w800,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
