import 'package:flutter/material.dart';

/* Text studies_title
    Autogenerated by FlutLab FTF Generator
  */
class StudiesTitle extends StatelessWidget {
  const StudiesTitle({super.key, required this.study});

  final String study;

  @override
  Widget build(BuildContext context) {
    return Text(
      study,
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: const TextStyle(
        height: 1.1530000141688757,
        fontSize: 14.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
