import 'package:flutter/material.dart';
import 'package:platonic/screens/flats_screen/widgets/widgets.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class FlatScrollSearchbarIconContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: 20.0,
      height: 20.0,
      child: SizedBox(
        width: 15.0,
        height: 15.0,
        child: FlatScrollSearchbarIcon(),
      ),
    );
  }
}
