import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/flat_provider/providers.dart';
import 'package:platonic/screens/flats_screen/widgets/widgets.dart';

/* Group searchbar
    Autogenerated by FlutLab FTF Generator
  */
class FlatScrollSearchbar extends ConsumerWidget {
  const FlatScrollSearchbar({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return TextField(
      onChanged: (text) =>
          ref.read(flatSearchBarProvider.notifier).state = text,
      style: const TextStyle(
          height: 1.1530000141688757,
          fontSize: 14.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Colors.black),
      decoration: InputDecoration(
        prefixIcon: const FlatScrollSearchbarIconContainer(),
        hintText: AppLocalizations.of(context)!.flatsSearchPlaceholder,
        hintStyle: const TextStyle(color: Color.fromARGB(255, 130, 130, 132)),
        counterText: "",
        errorStyle: const TextStyle(fontSize: 0.01),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 10.0,
        ),
        fillColor: const Color.fromARGB(255, 255, 255, 255),
        filled: true,
        enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(30.0),
            borderSide: BorderSide.none),
        focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(30.0),
            borderSide: BorderSide.none),
      ),
    );
  }
}
