import 'package:flutter/material.dart';
import 'package:platonic/helpers/mask/mask.dart';

/* Ellipse avatar
    Autogenerated by FlutLab FTF Generator
  */
class ReceivedMessageAvatar extends StatelessWidget {
  final String profileImage;

  const ReceivedMessageAvatar({super.key, required this.profileImage});
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 35.0,
      height: 35.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: Mask.fromSVGPath(
                'M35 17.5C35 27.165 27.165 35 17.5 35C7.83502 35 0 27.165 0 17.5C0 7.83502 7.83502 0 17.5 0C27.165 0 35 7.83502 35 17.5Z',
                offset: const Offset(0.0, 0.0),
                child: Image.network(
                  profileImage,
                  color: null,
                  fit: BoxFit.cover,
                  width: 35.0,
                  height: 35.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
            )
          ]),
    );
  }
}
