import 'package:flutter/material.dart';

/* Text body
    Autogenerated by FlutLab FTF Generator
  */
class ReceivedMessageText extends StatelessWidget {
  final String text;

  const ReceivedMessageText({super.key, required this.text});
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        text,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: const TextStyle(
          height: 1.152999997138977,
          fontSize: 16.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
