import 'package:flutter/material.dart';
import 'package:platonic/widgets/profile/meet_picutre_container/AddFrame.dart';
import 'package:platonic/widgets/profile/meet_picutre_container/AddContainer.dart';

/* Group add_button
    Autogenerated by FlutLab FTF Generator
  */
class AddButton extends StatelessWidget {
  const AddButton({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0,
      height: 80.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: 80.0,
              child: AddContainer(),
            ),
            Positioned(
              left: 15.0,
              top: null,
              right: 15.0,
              bottom: 15.0,
              width: null,
              height: 50.0,
              child: AddFrame(),
            )
          ]),
    );
  }
}
