import 'package:flutter/material.dart';

/* Rectangle container
    Autogenerated by FlutLab FTF Generator
  */
class AvatarContainer extends StatelessWidget {
  const AvatarContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100.0,
      height: 150.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          color: const Color.fromARGB(255, 43, 45, 46),
        ),
      ),
    );
  }
}
