import 'package:flutter/material.dart';

/* Rectangle container
    Autogenerated by FlutLab FTF Generator
  */
class StartContainer extends StatelessWidget {
  const StartContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 220.0,
      height: 60.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(30.0),
        boxShadow: const [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          color: const Color.fromARGB(255, 63, 141, 253),
        ),
      ),
    );
  }
}
