import 'package:flutter/material.dart';
import 'package:platonic/screens/start_screen/widgets/widgets.dart';

/* Group top
    Autogenerated by FlutLab FTF Generator
  */
class StartTop extends StatelessWidget {
  const StartTop({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      width: 340.0,
      height: 170.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 120.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 150.0,
              child: StartOriginal(),
            ),
            Positioned(
              left: 240.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 150.0,
              child: StartBlur(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 150.0,
              child: StartBlur(),
            )
          ]),
    );
  }
}
