import 'package:flutter/material.dart';

/* Text Enter your registered email below to receive password reset instruction
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPasswordInstructions extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Enter your registered email below to receive
password reset instruction''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.1530000141688757,
        fontSize: 14.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
