import 'package:flutter/material.dart';

/* Text account_login
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPasswordLogin extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLoginWidget'),
      child: Align(
        alignment: Alignment.center,
        child: RichText(
            overflow: TextOverflow.visible,
            textAlign: TextAlign.center,
            text: const TextSpan(
              style: TextStyle(
                height: 1.152999997138977,
                fontSize: 16.0,
                fontFamily: 'Gilroy',
                fontWeight: FontWeight.w300,
                color: Color.fromARGB(255, 255, 255, 255),

                /* letterSpacing: 0.0, */
              ),
              children: [
                TextSpan(
                  text: '''Remember password? ''',
                ),
                TextSpan(
                  text: '''Login''',
                  style: TextStyle(
                    color: Color.fromARGB(255, 63, 141, 253),

                    /* letterSpacing: null, */
                  ),
                )
              ],
            )),
      ),
    );
  }
}
