import 'package:flutter/material.dart';

/* Rectangle image 1
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPasswordIlustration extends StatelessWidget {
  const ForgotPasswordIlustration({super.key});

  @override
  Widget build(BuildContext context) {
    return Image.asset(
      "assets/images/forgot_password_illustration.png",
      color: null,
      fit: BoxFit.cover,
      width: 176.0,
      height: 173.0,
      colorBlendMode: BlendMode.dstATop,
    );
  }
}
