import 'package:flutter/material.dart';

/* Rectangle container
    Autogenerated by FlutLab FTF Generator
  */
class PersonalInputContainer extends StatelessWidget {
  const PersonalInputContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 258.0,
      height: 38.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
        border: Border.all(
          width: 1.0,
          color: const Color.fromARGB(255, 43, 45, 46),
        ),
      ),
    );
  }
}
