import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

/* Text text
    Autogenerated by FlutLab FTF Generator
  */
class ChatTimestampText extends StatelessWidget {
  final int timestamp;

  const ChatTimestampText({super.key, required this.timestamp});

  @override
  Widget build(BuildContext context) {
    DateTime dateTime =
        DateTime.fromMillisecondsSinceEpoch(timestamp, isUtc: true);

    return Align(
      alignment: Alignment.center,
      child: RichText(
          overflow: TextOverflow.visible,
          textAlign: TextAlign.center,
          text: TextSpan(
              style: const TextStyle(
                height: 1.2250000635782878,
                fontSize: 12.0,
                fontFamily: 'Gilroy',
                fontWeight: FontWeight.w800,
                color: Color.fromARGB(255, 255, 255, 255),

                /* letterSpacing: 0.0, */
              ),
              children: [
                TextSpan(
                  text: DateFormat('EEEE').format(dateTime),
                ),
                const TextSpan(text: ' '),
                TextSpan(
                  text: DateFormat('HH:mm').format(dateTime),
                  style: const TextStyle(
                    fontFamily: 'Gilroy',
                    fontWeight: FontWeight.w300,
                    /* letterSpacing: null, */
                  ),
                )
              ])),
    );
  }
}
