import 'package:flutter/material.dart';

/* Group book
    Autogenerated by FlutLab FTF Generator
  */
class BookMark extends StatelessWidget {
  final bool bookMarkActive;

  const BookMark({Key? key, required this.bookMarkActive}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: 30.0,
      height: 30.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Container(
        alignment: Alignment.center,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(5.0),
          color: Color.fromARGB(255, 43, 45, 46),
        ),
        child: Icon(
          bookMarkActive ? Icons.bookmark_outlined : Icons.bookmark_border,
          size: 20.0,
          color: bookMarkActive
              ? Color.fromARGB(255, 232, 236, 0)
              : Color.fromARGB(255, 255, 255, 255),
        ),
      ),
    );
  }
}
