import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/constants/constants.dart';
import 'package:platonic/providers/shared_preferences_provider/providers.dart';

/* Rectangle background
    Autogenerated by FlutLab FTF Generator
  */
class FlatScrollBackground extends ConsumerWidget {
  final String image;

  const FlatScrollBackground({Key? key, required this.image}) : super(key: key);
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Container(
      decoration: BoxDecoration(
          borderRadius: const BorderRadius.vertical(top: Radius.circular(10.0)),
          image: DecorationImage(
              image: NetworkImage(
                image,
                headers: {
                  'Authorization':
                      'Bearer ${ref.read(sharedPreferencesProvider).getString(FIREBASE_TOKEN_ID_KEY) ?? ''}'
                },
              ),
              fit: BoxFit.cover)),
    );
  }
}
