import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/domains/flat_repository/src/models/models.dart';
import 'package:platonic/providers/flat_provider/providers.dart';
import 'package:platonic/providers/user_provider/providers.dart';
import 'package:platonic/screens/create_flat_screen/step1_screen/widgets/widgets.dart';
import 'widgets.dart';

/* Rectangle wallpaper
    Autogenerated by FlutLab FTF Generator
  */
class FlatsScrollHeader extends ConsumerWidget {
  const FlatsScrollHeader({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final myUser = ref.read(appUserProvider);

    void toggleCreateFlatScreen() {
      Navigator.pushNamed(context, '/GeneratedStep1Widget');

      ref.read(flatCreateProvider.notifier).state =
          ref.read(flatCreateProvider).copyWith(owner: myUser, transports: [
        TransportModel(
            id: 1,
            name: 'Train',
            icon: Icons.directions_train,
            minutes: 0,
            university: myUser.university!)
      ]);
    }

    return Container(
      padding: const EdgeInsets.symmetric(vertical: 16.0),
      decoration: BoxDecoration(
        color: Colors.black.withOpacity(.5),
      ),
      child: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: Row(
            children: [
              const SizedBox(
                width: 25.0,
                height: 25.0,
                child: NavigateBeforeIconContainer(
                  color: Colors.white,
                ),
              ),
              const SizedBox(
                width: 16.0,
              ),
              Flexible(
                child: SizedBox(
                  height: 38.0,
                  child: FlatScrollSearchbar(),
                ),
              ),
              const SizedBox(
                width: 16.0,
              ),
              GestureDetector(
                  onTap: toggleCreateFlatScreen, child: CreateFlatButton())
            ],
          ),
        ),
      ),
    );
  }
}
