import 'package:flutter/material.dart';
import 'package:platonic/helpers/transform/transform.dart';
import 'package:platonic/screens/profile_screen/widgets/widgets.dart';

/* Instance backbutton
    Autogenerated by FlutLab FTF Generator
  */
class BackButtonContainer extends StatelessWidget {
  const BackButtonContainer({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pop(context),
      child: SizedBox(
        width: 35.0,
        height: 35.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 35.0;

                  double percentHeight = 1.0;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 35.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: const BackButtonBackground())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5714285714285714;

                  final double height =
                      constraints.maxHeight * 0.5714285714285714;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.22857142857142856,
                        y: constraints.maxHeight * 0.2,
                        z: 0,
                        child: SizedBox(
                          width: width,
                          height: height,
                          child: const BackButtonWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
