import 'package:flutter/material.dart';
import 'package:flutterapp/domain/university_repository/src/models/university_model.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flat_scroll_transport/flat_scroll_transport_title.dart';

/* Group transport
    Autogenerated by FlutLab FTF Generator
  */
class FlatScrollTransport extends StatelessWidget {
  final IconData child;
  final int minutes;
  final University university;

  const FlatScrollTransport(
      {Key? key,
      required this.child,
      required this.minutes,
      required this.university})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Icon(
        child,
        color: Color.fromARGB(255, 130, 130, 132),
        size: 10.0,
      ),
      SizedBox(
        width: 6.0,
      ),
      FlatScrollTransportTitle(
        minutes: minutes,
        university: university,
      ),
    ]);
  }
}
