import 'package:platonic/domains/university_repository/university_repository.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';

/* Text transporttitle
    Autogenerated by FlutLab FTF Generator
  */
class FlatScrollTransportTitle extends StatelessWidget {
  final int minutes;
  final University university;

  const FlatScrollTransportTitle({
    Key? key,
    required this.minutes,
    required this.university,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Text(
      AppLocalizations.of(context)!
          .flatsTransportTitle(minutes, university.simpleName.toUpperCase()),
      overflow: TextOverflow.ellipsis,
      textAlign: TextAlign.left,
      style: const TextStyle(
        fontSize: 10.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 130, 130, 132),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
