import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';
import 'package:platonic/helpers/transform/transform.dart';

/* Line line
    Autogenerated by FlutLab FTF Generator
  */
class PreferencesMonthSliderLine extends StatelessWidget {
  const PreferencesMonthSliderLine({super.key});

  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: 0.00,
        c: -0.00,
        d: 1.00,
        child: SizedBox(
          width: 358.0013122558594,
          height: 2.0,
          child: SvgWidget(painters: [
            SvgPathPainter.stroke(
              2.0,
              strokeCap: StrokeCap.round,
              strokeJoin: StrokeJoin.miter,
            )
              ..addPath(
                  'M1 -2C0.447715 -2 0 -1.55228 0 -1C0 -0.447715 0.447715 0 1 0L1 -2ZM357.001 0C357.554 0 358.001 -0.447715 358.001 -1C358.001 -1.55228 357.554 -2 357.001 -2L357.001 0ZM1 -1.11022e-16L357.001 -1.11022e-16L357.001 -2L1 -2L1 -1.11022e-16Z')
              ..color = const Color.fromARGB(255, 130, 130, 132),
          ]),
        ));
  }
}
