import 'package:flutter/material.dart';
import 'package:platonic/widgets/settings/SettingsTitle.dart';
import 'package:platonic/widgets/settings/settings_select/SettingsSelectChild.dart';

/* Group studies_to_meet
    Autogenerated by FlutLab FTF Generator
  */
class SettingsSelect extends StatelessWidget {
  final String placeholder, title;
  final Widget settingsDialog;

  const SettingsSelect(
      {Key? key,
      required this.placeholder,
      required this.title,
      required this.settingsDialog})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 38.0,
      child: Row(children: [
        SizedBox(
          width: 116.0,
          height: 16.0,
          child: SettingsTitle(
            title: title,
          ),
        ),
        const SizedBox(
          width: 21.0,
        ),
        SettingsSelectChild(
          settingsDialog: settingsDialog,
          placeholder: placeholder,
        ),
      ]),
    );
  }
}
