import 'package:platonic/screens/auth_screen/login/widgets/widgets.dart';
import 'package:platonic/screens/auth_screen/widgets/widgets.dart';
import 'package:platonic/screens/forgot_password_screen/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:platonic/screens/profile_screen/widgets/widgets.dart';

/* Frame forgot_password
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPasswordScreen extends StatelessWidget {
  const ForgotPasswordScreen({super.key});

  @override
  Widget build(BuildContext context) {
    void toggleSendEmail() {}

    return Scaffold(
      backgroundColor: const Color.fromARGB(255, 27, 26, 29),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child:
              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            const SizedBox(
                width: 35.0, height: 35.0, child: BackButtonContainer()),
            const SizedBox(
              height: 22.0,
            ),
            const SizedBox(
              height: 34.0,
              child: AuthenticationTitleText(title: '''Forgot Password?'''),
            ),
            const SizedBox(
              height: 22.0,
            ),
            const SizedBox(
              height: 34.0,
              child: ForgotPasswordInstructions(),
            ),
            const SizedBox(
              height: 22.0,
            ),
            const Align(
              alignment: Alignment.center,
              child: SizedBox(
                height: 173.0,
                child: ForgotPasswordIlustration(),
              ),
            ),
            const SizedBox(
              height: 22.0,
            ),
            const SizedBox(height: 18.0, child: LoginTitle(title: '''Email''')),
            const SizedBox(
              height: 5.0,
            ),
            const SizedBox(
              height: 38.0,
              child: ForgotPasswordEmailInput(),
            ),
            const SizedBox(
              height: 32.0,
            ),
            GestureDetector(
              onTap: toggleSendEmail,
              child: const SizedBox(
                height: 44.0,
                child: AuthenticationButtonContainer(
                  text: '''Send Email''',
                ),
              ),
            ),
            const SizedBox(
              height: 22.0,
            ),
            const SizedBox(
              height: 20.0,
              child: RememberPassword(),
            ),
          ]),
        ),
      ),
    );
  }
}
