import 'package:flutter/material.dart';
import 'package:flutterapp/screens/forgot_password_screen/widgets/forgot_password_email_input.dart';
import 'package:flutterapp/screens/forgot_password_screen/widgets/forgot_password_instructions.dart';
import 'package:flutterapp/screens/forgot_password_screen/widgets/forgot_password_ilustration.dart';
import 'package:flutterapp/screens/forgot_password_screen/widgets/forgot_password_login.dart';

/* Frame forgot_password
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPasswordScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromARGB(255, 27, 26, 29),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child:
              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Positioned(
              left: 0.0,
              top: 573.0,
              right: null,
              bottom: null,
              width: 392.0,
              height: 20.0,
              child: ForgotPasswordLogin(),
            ),
            /*  
           Send button
           Positioned(
              left: 16.0,
              top: 497.0,
              right: null,
              bottom: null,
              width: 358.0,
              height: 44.0,
              child: GeneratedAuthentication_buttonWidget3(),
            ), */
            Positioned(
              left: 0.0,
              top: 155.0,
              right: null,
              bottom: null,
              width: 392.0,
              height: 34.0,
              child: ForgotPasswordInstructions(),
            ),
            Positioned(
              left: 16.0,
              top: 404.0,
              right: null,
              bottom: null,
              width: 358.0,
              height: 61.0,
              child: ForgotPasswordEmailInput(),
            ),
            Positioned(
              left: 107.0,
              top: 209.0,
              right: null,
              bottom: null,
              width: 176.0,
              height: 173.0,
              child: ForgotPasswordIlustration(),
            ),
            /* 
           Forgot passwrod title
            Positioned(
              left: 50.0,
              top: 102.0,
              right: null,
              bottom: null,
              width: 289.0,
              height: 34.0,
              child: GeneratedAuthentication_titleWidget5(),
            ) */
          ]),
        ),
      ),
    );
  }
}
