import 'package:flutter/material.dart';

/* Text meet_description
    Autogenerated by FlutLab FTF Generator
  */
class MeetDescription extends StatelessWidget {
  const MeetDescription({super.key});

  @override
  Widget build(BuildContext context) {
    return const Align(
      alignment: Alignment.center,
      child: Text(
        '''Meet is a functionality that automatically matches you with a person of your choice every day at 3 pm''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.152999997138977,
          fontSize: 16.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 130, 130, 132),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
