import 'package:flutter/material.dart';
import 'package:platonic/screens/register_detail_screen/widgets/widgets.dart';

/* Group name_input
    Autogenerated by FlutLab FTF Generator
  */
class NameInput extends StatelessWidget {
  const NameInput({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      height: 38.0,
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        SizedBox(
          width: 50.0,
          height: 38.0,
          child: PersonalTitle(
            title: '''Name''',
          ),
        ),
        SizedBox(
          width: 258.0,
          height: 38.0,
          child: PersonalNameInput(),
        ),
      ]),
    );
  }
}
