import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/register_detail_provider/register_detail_provider.dart';
import 'package:platonic/screens/dialog_screen/faculty_dialog_screen.dart';
import 'package:platonic/screens/dialog_screen/study_dialog_screen.dart';
import 'package:platonic/screens/dialog_screen/university_dialog_screen.dart';
import 'package:platonic/screens/register_detail_screen/widgets/widgets.dart';

/* Frame personal
    Autogenerated by FlutLab FTF Generator
  */
class RegisterDetailPersonal extends ConsumerWidget {
  const RegisterDetailPersonal({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final registerDetailState = ref.watch(registerDetailProvider);

    return SizedBox(
      height: 303.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const SizedBox(
          height: 38.0,
          child: NameInput(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        const SizedBox(
          height: 38.0,
          child: AgeInput(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        const SizedBox(
          height: 38.0,
          child: PersonalSwitch(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: PersonalSelect(
            placeholder:
                registerDetailState.university?.name ?? 'Your university',
            title: '''University''',
            personalDialog: const UniversityDialogScreen(
              isMeetSettings: false,
            ),
          ),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: PersonalSelect(
            placeholder:
                registerDetailState.faculty?.facultyName ?? 'Your faculty',
            title: '''Faculty''',
            personalDialog: const FacultyDialogScreen(
              isMeetSettings: false,
            ),
          ),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: PersonalSelect(
            placeholder: registerDetailState.study?.name ?? 'Your studies',
            title: '''Studies''',
            personalDialog: const StudyDialogScreen(),
          ),
        )
      ]),
    );
  }
}
