import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/dialog_provider/is_meet_settings_dialog_provider.dart';
import 'package:platonic/providers/user_provider/providers.dart';
import 'package:platonic/screens/settings_screen/widgets/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

/* Frame meet
    Autogenerated by FlutLab FTF Generator
  */
class RegisterDetailMeet extends ConsumerWidget {
  const RegisterDetailMeet({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final userState = ref.watch(appUserProvider);

    void toggleUniversity() {
      ref.read(isMeetSettingsDialogProvider.notifier).state = true;

      Navigator.pushNamed(context, '/UniversityDialogScreen');
    }

    void toggleFaculty() {
      ref.read(isMeetSettingsDialogProvider.notifier).state = true;

      Navigator.pushNamed(context, '/FacultyDialogScreen');
    }

    return SizedBox(
      height: 138.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const SizedBox(
          height: 32.0,
          child: SexToMeet(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: SettingsSelect(
            placeholder: userState.universityToMeet != null &&
                    userState.universityToMeet!.name.isNotEmpty
                ? userState.universityToMeet!.name
                : AppLocalizations.of(context)!
                    .registerDetailMeetUniversityPlaceholderText,
            title: AppLocalizations.of(context)!
                .registerDetailMeetUniversityTtitle,
            toggleDialog: toggleUniversity,
          ),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: SettingsSelect(
            placeholder: userState.facultiesToMeet != null &&
                    userState.facultiesToMeet!.isNotEmpty
                ? '${userState.facultiesToMeet!.first.facultyName} +${userState.facultiesToMeet!.length - 1}'
                : AppLocalizations.of(context)!
                    .registerDetailMeetFacultiesPlaceholderText,
            title:
                AppLocalizations.of(context)!.registerDetailMeetFacultiesTitle,
            toggleDialog: toggleFaculty,
          ),
        )
      ]),
    );
  }
}
