import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/dialog_provider/is_meet_settings_dialog_provider.dart';
import 'package:platonic/providers/user_provider/providers.dart';
import 'package:platonic/screens/settings_screen/widgets/widgets.dart';

/* Frame meet
    Autogenerated by FlutLab FTF Generator
  */
class RegisterDetailMeet extends ConsumerWidget {
  const RegisterDetailMeet({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final userRegisterDetailState = ref.watch(userRegisterDetailProvider);

    void toggleUniversity() {
      ref.read(isMeetSettingsDialogProvider.notifier).state = true;

      Navigator.pushNamed(context, '/UniversityDialogScreen');
    }

    void toggleFaculty() {
      ref.read(isMeetSettingsDialogProvider.notifier).state = true;

      Navigator.pushNamed(context, '/FacultyDialogScreen');
    }

    return SizedBox(
      height: 138.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const SizedBox(
          height: 32.0,
          child: SexToMeet(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: SettingsSelect(
            placeholder: userRegisterDetailState.universityToMeet != null &&
                    userRegisterDetailState.universityToMeet!.name.isNotEmpty
                ? userRegisterDetailState.universityToMeet!.name
                : 'Your university to meet',
            title: '''University to meet''',
            toggleDialog: toggleUniversity,
          ),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: SettingsSelect(
            placeholder: userRegisterDetailState.facultiesToMeet != null &&
                    userRegisterDetailState.facultiesToMeet!.isNotEmpty
                ? '${userRegisterDetailState.facultiesToMeet!.first.facultyName} +${userRegisterDetailState.facultiesToMeet!.length - 1}'
                : 'Your faculties to meet',
            title: '''Faculties to meet''',
            toggleDialog: toggleFaculty,
          ),
        )
      ]),
    );
  }
}
