import 'package:flutter/material.dart';
import 'package:platonic/screens/match_screen/widgets/widgets.dart';

/* Group big_favourite
    Autogenerated by FlutLab FTF Generator
  */
class MatchBigFavourite extends StatelessWidget {
  const MatchBigFavourite({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      width: 32.0,
      height: 32.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 32.0,
              height: 32.0,
              child: MatchBigFavouriteContainer(),
            ),
            Positioned(
              left: 6.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: MatchBigFavouriteIconContainer(),
            )
          ]),
    );
  }
}
