import 'package:flutter/material.dart';
import 'package:platonic/helpers/transform/transform.dart';
import 'package:platonic/screens/match_screen/widgets/widgets.dart';

/* Frame favorite_FILL1_wght400_GRAD0_opsz48 1
    Autogenerated by FlutLab FTF Generator
  */
class MatchBigFavouriteIconContainer extends StatelessWidget {
  const MatchBigFavouriteIconContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: SizedBox(
        width: 20.0,
        height: 20.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8333333015441895;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 16.66666603088379;

                  double percentHeight = 0.7635416984558105;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      15.270833969116211;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08333333134651184,
                        translateY: constraints.maxHeight * 0.11041667461395263,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: const MatchBigFavouriteIcon())
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
