import 'package:flutter/material.dart';

/* Ellipse Ellipse 12
    Autogenerated by FlutLab FTF Generator
  */
class MatchBigFavouriteContainer extends StatelessWidget {
  const MatchBigFavouriteContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
        width: 32.0,
        height: 32.0,
        decoration: const BoxDecoration(
          shape: BoxShape.circle,
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Color(0xFFFF87B9),
              Color(0xFFFF5A8D),
              Color(0xFFCFB4FF),
            ],
            stops: [0.1, 0.5, 0.9],
          ),
        ));
  }
}
