import 'package:flutter/material.dart';

/* Text placeholder
    Autogenerated by FlutLab FTF Generator
  */
class AuthPlaceholderText extends StatelessWidget {
  final String text;

  const AuthPlaceholderText({Key? key, required this.text}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        text,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: const TextStyle(
          height: 1.1530000141688757,
          fontSize: 14.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
