import 'package:flutter/material.dart';

/* Text title_placeholder
    Autogenerated by FlutLab FTF Generator
  */
class CreateInput extends StatelessWidget {
  const CreateInput({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: TextField(
        keyboardType: TextInputType.multiline,
        textInputAction: TextInputAction.newline,
        maxLines: null,
        textAlign: TextAlign.center,
        maxLength: 200,
        decoration: InputDecoration(
          counter: SizedBox.shrink(),
          hintText: "Tap to write",
          hintStyle: TextStyle(
            height: 1.2,
            fontSize: 35.0,
            fontFamily: 'DezenPro',
            fontWeight: FontWeight.w400,
            color: Color.fromARGB(255, 255, 255, 255),
          ),
          border: InputBorder.none,
          contentPadding: EdgeInsets.symmetric(horizontal: 32.0),
        ),
        style: TextStyle(
          height: 1.2,
          fontSize: 35.0,
          fontFamily: 'DezenPro',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 255, 255, 255),
        ),
      ),
    );
  }
}
