import 'package:flutter/material.dart';
import 'package:platonic/widgets/home/HomeTopbar.dart';
import 'package:platonic/widgets/home/MeetContainer.dart';
import 'package:platonic/widgets/home/MessagesContainer.dart';
import 'package:platonic/widgets/home/StoriesContainer.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
*/
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color.fromARGB(255, 27, 26, 29),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(children: [
            const SizedBox(
              height: 35.0,
              child: HomeTopbar(),
            ),
            const SizedBox(
              height: 22.0,
            ),
            const SizedBox(
              height: 163.0,
              child: StoriesContainer(),
            ),
            const SizedBox(
              height: 32.0,
            ),
            SizedBox(
              height: 158.0,
              child: MeetContainer(),
            ),
            const SizedBox(
              height: 32.0,
            ),
            const MessagesContainer(),
          ]),
        ),
      ),
    );
  }
}
