import 'package:flutter/material.dart';

/* Rectangle apple
    Autogenerated by FlutLab FTF Generator
  */
class Apple extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.68421173095703,
      height: 21.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/d82bd87a47600a88b85953e36865534a3423c2a2.png",
          color: null,
          fit: BoxFit.cover,
          width: 17.68421173095703,
          height: 21.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
