import 'package:flutter/material.dart';
import 'widgets/widgets.dart';

/* Frame step1
    Autogenerated by FlutLab FTF Generator
  */
class Step1Screen extends StatelessWidget {
  const Step1Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        resizeToAvoidBottomInset: false,
        backgroundColor: const Color.fromARGB(255, 27, 26, 29),
        body: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              const CreateFlatMap(),
              Column(
                children: [
                  Container(
                    decoration: const BoxDecoration(
                      color: Color.fromARGB(102, 255, 255, 255),
                      boxShadow: [
                        BoxShadow(
                          color: Color.fromARGB(63, 255, 255, 255),
                          offset: Offset(0.0, 4.0),
                          blurRadius: 8.0,
                        )
                      ],
                    ),
                    child: const SafeArea(
                      child: Padding(
                        padding: EdgeInsets.all(16.0),
                        child: NavigateBefore(
                          color: Colors.black,
                          title: '''Step 1-4''',
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(
                    height: 32.0,
                  ),
                  const Expanded(
                    child: Padding(
                      padding: EdgeInsets.symmetric(horizontal: 32.0),
                      child: Column(
                        children: [
                          CreateFlatDetailSearch(),
                          CreateFlatAddressSuggestion()
                        ],
                      ),
                    ),
                  ),
                  const Expanded(child: SizedBox()),
                  const Padding(
                    padding: EdgeInsets.all(32.0),
                    child: SizedBox(
                      height: 44.0,
                      child: CreateFlatDetailButton(
                        route: '/Step2Screen',
                        text: '''Confirm Address''',
                      ),
                    ),
                  )
                ],
              ),
            ]));
  }
}
