import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutterapp/providers/flat_provider/flat_scroll_provider.dart';
import 'package:flutterapp/providers/flat_provider/flats_scroll_provider.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flat_scroll_item.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flats_scroll_header.dart';

/* Frame flats
    Autogenerated by FlutLab FTF Generator
  */

class FlatsScreen extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final flatsScrollState = ref.watch(flatsScrollProvider);

    void toggleFlatDetailScreen() {
      Navigator.pushNamed(context, '/GeneratedDetailsWidget');
    }

    return Scaffold(
      backgroundColor: Color.fromARGB(255, 27, 26, 29),
      body: flatsScrollState.when(
        data: (flats) => Column(
          children: [
            FlatsScrollHeader(),
            Expanded(
                child: ListView.separated(
              padding: EdgeInsets.symmetric(vertical: 22.0, horizontal: 22.0),
              itemCount: flats.length,
              separatorBuilder: (context, index) => SizedBox(
                height: 22.0,
              ),
              itemBuilder: (context, index) {
                return GestureDetector(
                  onTap: toggleFlatDetailScreen,
                  child: SizedBox(
                    height: 225.0,
                    child: ProviderScope(overrides: [
                      flatScrollProvider.overrideWithValue(flats[index])
                    ], child: FlatScrollItem()),
                  ),
                );
              },
            ))
          ],
        ),
        loading: () => const Center(
          child: CircularProgressIndicator(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
        error: (error, stackTrace) {
          return Text(error.toString());
        },
      ),
    );
  }
}
