import 'package:flutter/material.dart';
import 'widgets.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class CreateFlatDetailSearchIconContainer extends StatelessWidget {
  const CreateFlatDetailSearchIconContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: 20.0,
      height: 20.0,
      child: const CreateFlatDetailSearchIcon(),
    );
  }
}
