import 'package:flutter/material.dart';
import 'package:platonic/widgets/match/users_images/small_favourite/MatchSmallFavouriteContainer.dart';
import 'package:platonic/widgets/match/users_images/small_favourite/MatchSmallFavouriteIconContainer.dart';

/* Group smaller_favourite
    Autogenerated by FlutLab FTF Generator
  */
class MatchSmallFavourite extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.588457107543945,
      height: 24.588457107543945,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 9.0,
              top: 2.5601821107557043e-8,
              right: null,
              bottom: null,
              width: 18.0,
              height: 18.0,
              child: MatchSmallFavouriteContainer(),
            ),
            Positioned(
              left: 10.464111328125,
              top: 5.464101791381836,
              right: null,
              bottom: null,
              width: 10.0,
              height: 10.0,
              child: MatchSmallFavouriteIconContainer(),
            )
          ]),
    );
  }
}
