import 'package:flutter/material.dart';

/* Text Delete
    Autogenerated by FlutLab FTF Generator
  */
class DeleteButtonText extends StatelessWidget {
  const DeleteButtonText({super.key});

  @override
  Widget build(BuildContext context) {
    return const Text(
      '''Delete''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.1530000141688757,
        fontSize: 14.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 255, 0, 76),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
