import 'package:flutter/material.dart';
import 'package:platonic/screens/settings_screen/widgets/widgets.dart';

/* Group studies_to_meet
    Autogenerated by FlutLab FTF Generator
  */
class SettingsSelect extends StatelessWidget {
  final String placeholder, title;
  final Function() toggleDialog;

  const SettingsSelect(
      {Key? key,
      required this.placeholder,
      required this.title,
      required this.toggleDialog})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 38.0,
      child: Row(children: [
        SizedBox(
          width: 116.0,
          height: 16.0,
          child: SettingsTitle(
            title: title,
          ),
        ),
        const SizedBox(
          width: 21.0,
        ),
        GestureDetector(
          onTap: toggleDialog,
          child: Container(
            width: 221.0,
            height: 37.9799919128418,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(10.0),
              color: const Color.fromARGB(255, 43, 45, 46),
            ),
            child: Row(children: [
              const SizedBox(
                width: 9.0,
              ),
              Expanded(
                child: SettingsSelectPlaceholder(
                  placeholder: placeholder,
                ),
              ),
              Container(
                alignment: Alignment.center,
                height: 21.0,
                width: 21.0,
                child: const SettingsSelectIcon(),
              ),
              const SizedBox(
                width: 9.0,
              ),
            ]),
          ),
        )
      ]),
    );
  }
}
