import 'package:flutter/material.dart';
import 'package:platonic/domains/http_repository/models/error_app_model.dart';

/* Text There’s an error with the authentication: the user or the password are not correct
    Autogenerated by FlutLab FTF Generator
  */
class ErrorText extends StatelessWidget {
  const ErrorText({super.key, required this.errorApp});

  final ErrorApp errorApp;

  @override
  Widget build(BuildContext context) {
    return Text(
      errorApp.getError(context),
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: const TextStyle(
        height: 1.152999997138977,
        fontSize: 16.0,
        fontFamily: 'Gilroy',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
