import 'package:flutter/material.dart';

/* Rectangle apple
    Autogenerated by FlutLab FTF Generator
  */
class Apple extends StatelessWidget {
  const Apple({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 17.68421173095703,
      height: 21.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/apple_icon.png",
          color: null,
          fit: BoxFit.cover,
          width: 17.68421173095703,
          height: 21.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
