import 'package:platonic/widgets/settings/SettingsTitle.dart';
import 'package:platonic/widgets/settings/meet_switch/MeetSwitch.dart';
import 'package:flutter/material.dart';

/* Group sex_to_meet
    Autogenerated by FlutLab FTF Generator
  */
class SexToMeet extends StatelessWidget {
  const SexToMeet({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 32.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: const Row(children: [
        SizedBox(
            width: 116.0,
            height: 16.0,
            child: SettingsTitle(
              title: '''Sex to meet''',
            )),
        SizedBox(
          width: 21.0,
        ),
        MeetSwitch(),
      ]),
    );
  }
}
