import 'package:platonic/providers/shared_preferences_provider/providers.dart';
import 'package:platonic/screens/start_screen/widgets/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/constants/constants.dart';
import 'package:flutter/material.dart';

/* Frame started
    Autogenerated by FlutLab FTF Generator
  */
class StartScreen extends ConsumerWidget {
  const StartScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    Future<void> toggleGetStarted() async {
      await ref
          .read(sharedPreferencesProvider)
          .setBool(FIRST_TIME_USING_APP_KEY, false);

      Navigator.pushNamedAndRemoveUntil(
          context, '/HomeScreen', (route) => false);
    }

    return Scaffold(
        backgroundColor: const Color.fromARGB(255, 27, 26, 29),
        body: Column(
          children: [
            const SizedBox(
              height: 442.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  clipBehavior: Clip.none,
                  children: [
                    Positioned(
                      left: 0.0,
                      top: -20.0,
                      height: 447.0042724609375,
                      child: BackgroundDecoration(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: -68.0,
                      height: 510.0,
                      child: StartFrame(),
                    ),
                  ]),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(vertical: 32.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const SizedBox(
                      height: 86.0,
                      child: StartTitle(),
                    ),
                    const SizedBox(
                      height: 56.0,
                      child: StartSubtitle(),
                    ),
                    SizedBox(
                      height: 60.0,
                      child: GestureDetector(
                          onTap: toggleGetStarted, child: const StartButton()),
                    )
                  ],
                ),
              ),
            ),
          ],
        ));
  }
}
