import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/constants/constants.dart';
import 'package:platonic/helpers/mask/mask.dart';
import 'package:platonic/providers/shared_preferences_provider/providers.dart';

/* Ellipse avatar
    Autogenerated by FlutLab FTF Generator
  */
class ReceivedMessageAvatar extends ConsumerWidget {
  final String? profileImage;

  const ReceivedMessageAvatar({super.key, required this.profileImage});
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return SizedBox(
      width: 35.0,
      height: 35.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: Mask.fromSVGPath(
                'M35 17.5C35 27.165 27.165 35 17.5 35C7.83502 35 0 27.165 0 17.5C0 7.83502 7.83502 0 17.5 0C27.165 0 35 7.83502 35 17.5Z',
                offset: const Offset(0.0, 0.0),
                child: profileImage == null
                    ? Image.asset(
                        'assets/images/default_avatar.jpg',
                        fit: BoxFit.cover,
                        width: 35.0,
                        height: 35.0,
                        colorBlendMode: BlendMode.dstATop,
                      )
                    : Image.network(profileImage!,
                        fit: BoxFit.cover,
                        width: 35.0,
                        height: 35.0,
                        colorBlendMode: BlendMode.dstATop,
                        headers: {
                            'Authorization':
                                'Bearer ${ref.read(sharedPreferencesProvider).getString(FIREBASE_TOKEN_ID_KEY) ?? ''}'
                          }),
              ),
            )
          ]),
    );
  }
}
