import 'package:flutter/material.dart';
import 'package:platonic/screens/dialog_screen/widgets/widgets.dart';

/* Group option_selected
    Autogenerated by FlutLab FTF Generator
  */
class OptionSelected extends StatelessWidget {
  final bool isSelected, isBlue;
  final String name;

  const OptionSelected(
      {super.key,
      required this.isSelected,
      required this.isBlue,
      required this.name});

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      height: 42.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(
          width: 1.0,
          color: isSelected
              ? const Color.fromARGB(255, 33, 185, 252)
              : const Color.fromARGB(255, 255, 255, 255),
        ),
      ),
      child: Row(children: [
        const SizedBox(
          width: 14.0,
        ),
        SizedBox(
          width: 12.0,
          height: 12.0,
          child: CheckContainer(
            isBlue: isBlue,
            isSelected: isSelected,
          ),
        ),
        const SizedBox(
          width: 9.0,
        ),
        Expanded(
          child: DialogsTitle(
            isSelected: isSelected,
            name: name,
          ),
        ),
        const SizedBox(
          width: 14.0,
        ),
      ]),
    );
  }
}
