import 'package:flutterapp/screens/flats_screen/widgets/flats_scroll_navigate_before/flats_scroll_navigate_before_icon.dart';
import 'package:flutter/material.dart';

/* Frame navigate
    Autogenerated by FlutLab FTF Generator
  */
class FlatsScrollNavigateBeforeIconContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomeWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 20.0,
          height: 20.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                Positioned(
                  left: 6.9166669845581055,
                  top: 5.208333492279053,
                  right: null,
                  bottom: null,
                  width: 5.416666507720947,
                  height: 9.520833015441895,
                  child: FlatsScrollNavigateBeforeIcon(),
                )
              ]),
        ),
      ),
    );
  }
}
