import 'package:flutter/material.dart';
import 'flats_scroll_navigate_before_title.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flats_scroll_navigate_before/flats_scroll_navigate_before_icon_container.dart';

/* Group navigate
    Autogenerated by FlutLab FTF Generator
  */
class FlatsScrollNavigateBefore extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 20.0,
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        SizedBox(
          width: 20.0,
          height: 20.0,
          child: FlatsScrollNavigateBeforeIconContainer(),
        ),
        SizedBox(
          width: 54.0,
          height: 21.0,
          child: FlatsScrollNavigateBeforeTitle(),
        ),
        SizedBox(
          height: 20.0,
          width: 20.0,
        ),
      ]),
    );
  }
}
