import 'package:flutter/material.dart';
import 'package:platonic/widgets/register_detail/personal_select/PersonalSelectIcon.dart';
import 'package:platonic/widgets/register_detail/personal_select/PersonalSelectPlaceholder.dart';

/* Component selector
    Autogenerated by FlutLab FTF Generator
  */
class PersonalSelector extends StatefulWidget {
  final String placeholder;
  final Widget personalDialog;

  const PersonalSelector(
      {Key? key, required this.placeholder, required this.personalDialog})
      : super(key: key);

  @override
  State<PersonalSelector> createState() => _PersonalSelectorState();
}

class _PersonalSelectorState extends State<PersonalSelector> {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: _showDialogMethod,
      child: Container(
        width: 258.0,
        height: 38.0,
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10.0),
            color: const Color.fromARGB(255, 43, 45, 46)),
        child: Row(children: [
          const SizedBox(
            width: 9.0,
          ),
          Expanded(
              child: PersonalSelectPlaceholder(
            placeholder: widget.placeholder,
          )),
          Container(
              alignment: Alignment.center,
              height: 21.0,
              width: 21.0,
              child: const PersonalSelectIcon()),
          const SizedBox(
            width: 5.0,
          ),
        ]),
      ),
    );
  }

  void _showDialogMethod() {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return widget.personalDialog;
      },
    );
  }
}
