import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/* Text account_login
    Autogenerated by FlutLab FTF Generator
  */
class AlreadyHaveAnAccount extends ConsumerWidget {
  const AlreadyHaveAnAccount({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return GestureDetector(
      onTap: () => Navigator.pushNamedAndRemoveUntil(
          context, '/LoginScreen', (route) => false),
      child: Align(
        alignment: Alignment.center,
        child: RichText(
            overflow: TextOverflow.visible,
            textAlign: TextAlign.center,
            text: TextSpan(
              style: const TextStyle(
                height: 1.152999997138977,
                fontSize: 16.0,
                fontFamily: 'Gilroy',
                fontWeight: FontWeight.w300,
                color: Color.fromARGB(255, 255, 255, 255),

                /* letterSpacing: 0.0, */
              ),
              children: [
                TextSpan(
                  text:
                      AppLocalizations.of(context)!.registerAlreadyAccountText,
                ),
                const TextSpan(text: ' '),
                TextSpan(
                  text: AppLocalizations.of(context)!
                      .registerAlreadyAccountLoginText,
                  style: const TextStyle(
                    color: Color.fromARGB(255, 63, 141, 253),

                    /* letterSpacing: null, */
                  ),
                )
              ],
            )),
      ),
    );
  }
}
