import 'package:flutter/material.dart';

/* Text name
    Autogenerated by FlutLab FTF Generator
  */
class UserTitle extends StatelessWidget {
  final String name;

  const UserTitle({super.key, required this.name});

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        name,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: const TextStyle(
          height: 1.2250000635782878,
          fontSize: 18.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w800,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
