import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';

/* Ellipse outer_check
    Autogenerated by FlutLab FTF Generator
  */
class CheckOuter extends StatelessWidget {
  final bool isSelected;
  final bool isBlue;

  const CheckOuter({super.key, required this.isSelected, required this.isBlue});
  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      width: 12.0,
      height: 12.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M11 6C11 8.76142 8.76142 11 6 11L6 13C9.86599 13 13 9.86599 13 6L11 6ZM6 11C3.23858 11 1 8.76142 1 6L-1 6C-1 9.86599 2.13401 13 6 13L6 11ZM1 6C1 3.23858 3.23858 1 6 1L6 -1C2.13401 -1 -1 2.13401 -1 6L1 6ZM6 1C8.76142 1 11 3.23858 11 6L13 6C13 2.13401 9.86599 -1 6 -1L6 1Z')
          ..color = isSelected && isBlue
              ? const Color.fromARGB(255, 33, 185, 252)
              : const Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
