import 'package:flutter/material.dart';
import 'package:platonic/widgets/dialogs/check_container/CheckInner.dart';
import 'package:platonic/widgets/dialogs/check_container/CheckOuter.dart';

/* Group check_container
    Autogenerated by FlutLab FTF Generator
  */
class CheckContainer extends StatelessWidget {
  final bool isSelected;
  final bool isBlue;

  const CheckContainer(
      {super.key, required this.isSelected, required this.isBlue});
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 12.0,
      height: 12.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 12.0,
              height: 12.0,
              child: CheckOuter(
                isBlue: isBlue,
                isSelected: isSelected,
              ),
            ),
            Positioned(
              left: 2.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 8.0,
              height: 8.0,
              child: CheckInner(
                isBlue: isBlue,
                isSelected: isSelected,
              ),
            )
          ]),
    );
  }
}
