import 'package:flutter/material.dart';
import 'package:platonic/helpers/transform/transform.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Frame add
    Autogenerated by FlutLab FTF Generator
  */
class CreateContainer extends StatelessWidget {
  const CreateContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: SizedBox(
        width: 20.0,
        height: 20.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.5833333015441895;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      11.666666030883789;

                  double percentHeight = 0.5833333015441895;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.666666030883789;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.20833332538604737,
                        translateY: constraints.maxHeight * 0.20833332538604737,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: CreateIcon())
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
