import 'package:flutter/material.dart';
import 'package:platonic/domains/flat_repository/src/models/models.dart';
import 'widgets.dart';

/* Frame flatitem
    Autogenerated by FlutLab FTF Generator
  */
class FlatItemContent extends StatelessWidget {
  final String title, bathroom, bedroom;
  final int electricityPriceInCents, rentPricePerMonthInCents;
  final PropertyModel properties;

  const FlatItemContent(
      {super.key,
      required this.title,
      required this.bathroom,
      required this.bedroom,
      required this.electricityPriceInCents,
      required this.rentPricePerMonthInCents,
      required this.properties});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 5.0),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Expanded(
            child: FlatItemTitle(
          title: title,
        )),
        Expanded(
            child: FlatItemDirection(
          properties: properties,
        )),
        Expanded(
            child: FlatItemComodities(
          bathroom: bathroom,
          bedroom: bedroom,
        )),
        Expanded(
            child: FlatItemPrice(
          electricityPriceInCents: electricityPriceInCents,
          rentPricePerMonthInCents: rentPricePerMonthInCents,
        ))
      ]),
    );
  }
}
