import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/user_provider/providers.dart';

/* Rectangle flatimage
    Autogenerated by FlutLab FTF Generator
  */
class FlatItemImage extends ConsumerWidget {
  final String image;

  const FlatItemImage({super.key, required this.image});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Container(
      width: 110.0,
      height: 110.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Image.network(
          image,
          fit: BoxFit.cover,
          width: 110.0,
          height: 110.0,
          colorBlendMode: BlendMode.dstATop,
          headers: {'Authorization': 'Bearer ${ref.read(tokenIdProvider)}'},
        ),
      ),
    );
  }
}
