import 'package:flutter/material.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Group topbar
    Autogenerated by FlutLab FTF Generator
  */
class HomeTopbar extends StatelessWidget {
  const HomeTopbar({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 35.0,
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        Container(
          alignment: Alignment.center,
          height: 35.0,
          child: const HomeUniversityTitle(),
        ),
        const SizedBox(
          width: 135.0,
          height: 35.0,
          child: TopbarButtons(),
        ),
      ]),
    );
  }
}
