import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/helpers/transform/transform.dart';
import 'package:flutter/material.dart';
import 'package:platonic/providers/meet_provider/providers.dart';
import 'package:platonic/providers/user_provider/providers.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Component meet_item
    Autogenerated by FlutLab FTF Generator
  */
class MeetItem extends ConsumerWidget {
  const MeetItem({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final meetState = ref.watch(meetScrollProvider);

    return GestureDetector(
      onTap: () {
        ref.read(otherUserProvider.notifier).state = meetState.appUser;
        Navigator.pushNamed(context, '/OtherProfileScreen');
      },
      child: SizedBox(
        width: 80.0,
        height: 130.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.8461538461538461;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: SizedBox(
                          width: width,
                          height: height,
                          child: MeetBackground(
                            backgroundImage: meetState.appUser.profileImage!,
                          ),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.0625;

                  final double height =
                      constraints.maxHeight * 0.16153846153846155;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.8769230769230769,
                        z: 0,
                        child: SizedBox(
                          width: width,
                          height: height,
                          child: MeetTitle(
                            name: meetState.appUser.name,
                          ),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
