import 'package:flutter/material.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Group meets
    Autogenerated by FlutLab FTF Generator
  */
class MeetContainer extends StatelessWidget {
  const MeetContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      height: 138.0,
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        SizedBox(
          height: 18.0,
          child: HomeTitle(
            title: '''Meets''',
          ),
        ),
        SizedBox(
          height: 10.0,
        ),
        SizedBox(
          height: 110.0,
          child: MeetScroll(),
        ),
      ]),
    );
  }
}
