import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/chat_provider/providers.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Frame messages_scroll
    Autogenerated by FlutLab FTF Generator
  */
class MessagesScroll extends ConsumerWidget {
  const MessagesScroll({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final conversationsState = ref.watch(conversationsProvider);

    return Column(
        children: conversationsState.asMap().entries.map((e) {
      final index = e.key;
      final conversation = e.value;

      return ProviderScope(
        overrides: [conversationItemProvider.overrideWithValue(conversation)],
        child: Padding(
          padding:
              index != 0 ? const EdgeInsets.only(top: 10.0) : EdgeInsets.zero,
          child: const SizedBox(
            width: 358.0,
            height: 80.0,
            child: MessageItem(),
          ),
        ),
      );
    }).toList());
  }
}
