import 'package:flutter/material.dart';

/* Ellipse image
    Autogenerated by FlutLab FTF Generator
  */
class MessageImage extends StatelessWidget {
  final String? profileImage;

  const MessageImage({super.key, required this.profileImage});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
        width: 60.0,
        height: 60.0,
        child: Container(
            height: 60.0,
            width: 60.0,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              image: profileImage == null
                  ? const DecorationImage(
                      image: AssetImage(
                        'assets/images/default_avatar.jpg',
                      ),
                      fit: BoxFit.cover,
                    )
                  : DecorationImage(
                      image: NetworkImage(
                        profileImage!,
                      ),
                      fit: BoxFit.cover,
                    ),
            )));
  }
}
