import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/helpers/transform/transform.dart';
import 'package:platonic/providers/story_provider/providers.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Component story_item1
    Autogenerated by FlutLab FTF Generator
  */
class StoryItem extends ConsumerWidget {
  const StoryItem({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final storyState = ref.watch(storyScrollProvider);

    Future<void> toggleStoryScreen() async {
      ref.read(activeFacultyIdProvider.notifier).state = storyState.faculty.id;
      Navigator.pushNamed(context, '/StoryScreen');
    }

    return GestureDetector(
      onTap: toggleStoryScreen,
      child: Container(
        width: 100.0,
        height: 135.0,
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10.0),
            gradient: storyState.backgroundGradientIndex),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.25;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.18518518518518517;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.38,
                        translateY: constraints.maxHeight * 0.5111111111111111,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: StoryAvatar(url: storyState.user.profileImage))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 100.0;

                  double percentHeight = 0.3037037037037037;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 41.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: constraints.maxHeight * 0.6962962962962963,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: const StoryTitleContainer())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.92;

                  final double height =
                      constraints.maxHeight * 0.31851851851851853;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05,
                        y: constraints.maxHeight * 0.6962962962962963,
                        z: 0,
                        child: SizedBox(
                          width: width,
                          height: height,
                          child: StoryTitle(
                            faculty: storyState.faculty.facultyName!,
                          ),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    );
  }
}
