import 'package:flutter/material.dart';

/* Text story_title
    Autogenerated by FlutLab FTF Generator
  */
class StoryTitle extends StatelessWidget {
  final String faculty;

  const StoryTitle({super.key, required this.faculty});

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        faculty,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: const TextStyle(
          height: 1.1529999732971192,
          fontSize: 10.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
