import 'package:flutter/material.dart';
import 'package:flutterapp/domain/flat_repository/src/models/flats_scroll_model.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flat_amenities.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flat_scroll_info/flat_scroll_direction_title.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flat_scroll_info/flat_scroll_monthly_price.dart';
import 'package:flutterapp/screens/flats_screen/widgets/flat_scroll_transport/flat_scroll_transport.dart';
import 'flat_scroll_title.dart';

/* Frame university_info
    Autogenerated by FlutLab FTF Generator
  */
class FlatScrollInfo extends StatelessWidget {
  final FlatsScrollModel flatsScrollModel;

  const FlatScrollInfo({Key? key, required this.flatsScrollModel})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Expanded(
          child: FlatScrollTitle(
            title: flatsScrollModel.title,
          ),
        ),
        Expanded(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              FlatScrollDirectionTitle(
                name: flatsScrollModel.properties.name,
                city: flatsScrollModel.properties.city,
                state: flatsScrollModel.properties.state,
              ),
              FlatScrollTransport(
                child: flatsScrollModel.transport.icon,
                university: flatsScrollModel.transport.university,
                minutes: flatsScrollModel.transport.minutes,
              ),
            ],
          ),
        ),
        Expanded(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              FlatAmenities(
                bathroom: flatsScrollModel.bathroom,
                bedroom: flatsScrollModel.bedroom,
                built: flatsScrollModel.built,
              ),
              Flexible(
                  child: FlatScrollMonthlyPrice(
                rentPricePerMonthInCents:
                    flatsScrollModel.rentPricePerMonthInCents,
              ))
            ],
          ),
        ),
      ]),
    );
  }
}
