import 'package:flutter/material.dart';
import 'package:platonic/screens/home_screen/widgets/widgets.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
*/
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Color.fromARGB(255, 27, 26, 29),
      body: SafeArea(
        child: Padding(
          padding: EdgeInsets.all(16.0),
          child: Column(children: [
            SizedBox(
              height: 35.0,
              child: HomeTopbar(),
            ),
            SizedBox(
              height: 22.0,
            ),
            SizedBox(
              height: 163.0,
              child: StoriesContainer(),
            ),
            SizedBox(
              height: 32.0,
            ),
            SizedBox(
              height: 138.0,
              child: MeetContainer(),
            ),
            SizedBox(
              height: 32.0,
            ),
            MessagesContainer(),
          ]),
        ),
      ),
    );
  }
}
