import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class DetailAddTenantIcon extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.666666984558105,
      height: 11.666666984558105,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.20833 11.6667L5.20833 6.45833L0 6.45833L0 5.20833L5.20833 5.20833L5.20833 0L6.45833 0L6.45833 5.20833L11.6667 5.20833L11.6667 6.45833L6.45833 6.45833L6.45833 11.6667L5.20833 11.6667Z')
          ..color = Color.fromARGB(255, 63, 141, 253),
      ]),
    );
  }
}
