import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';

/* Text title
    Autogenerated by FlutLab FTF Generator
  */
class DetailAddTenantInput extends ConsumerWidget {
  final int flatId;

  const DetailAddTenantInput({super.key, required this.flatId});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    Future<void> toggleAddFlatTenant(String email) async {
      await ref
          .read(flatProvider.notifier)
          .addOrRemoveTenantFromFlat(email: email, flatId: flatId);
    }

    return TextFormField(
      onFieldSubmitted: toggleAddFlatTenant,
      textInputAction: TextInputAction.send,
      keyboardType: TextInputType.emailAddress,
      maxLines: 1,
      style: const TextStyle(
          height: 1.1530000141688757,
          fontSize: 14.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255)),
      decoration: InputDecoration(
        hintText: '''hello@example.com''',
        hintStyle: TextStyle(color: Colors.grey[400]),
        counterText: "",
        errorStyle: const TextStyle(fontSize: 0.01),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 10.0,
        ),
        enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10.0),
          borderSide: BorderSide.none,
        ),
        errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none),
        focusedErrorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none),
      ),
    );
  }
}
