import 'package:flutter/material.dart';
import 'package:platonic/helpers/mask/mask.dart';

/* Ellipse avatar
    Autogenerated by FlutLab FTF Generator
  */
class UserAvatarImage extends StatelessWidget {
  const UserAvatarImage({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 100.0,
      height: 100.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: Mask.fromSVGPath(
                'M100 50C100 77.6142 77.6142 100 50 100C22.3858 100 0 77.6142 0 50C0 22.3858 22.3858 0 50 0C77.6142 0 100 22.3858 100 50Z',
                offset: const Offset(0.0, 0.0),
                child: Image.asset(
                  "assets/images/11c97a1e48f1dc3e40998507942a19e99392643f.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 100.0,
                  height: 100.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
            )
          ]),
    );
  }
}
