import 'package:flutter/material.dart';

/* Rectangle blue_container
    Autogenerated by FlutLab FTF Generator
  */
class PersonalBlueContainer extends StatelessWidget {
  const PersonalBlueContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 130.0,
      height: 34.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          color: Color.fromARGB(255, 63, 141, 253),
        ),
      ),
    );
  }
}
