import 'package:flutter/material.dart';
import 'package:platonic/helpers/localization/features_localization.dart';

/* Text title
    Autogenerated by FlutLab FTF Generator
  */
class FeaturesListText extends StatelessWidget {
  final String text;

  const FeaturesListText({Key? key, required this.text}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      localizationToFeature(key: text, context: context),
      overflow: TextOverflow.ellipsis,
      textAlign: TextAlign.center,
      maxLines: 1,
      style: const TextStyle(
        height: 1.3020000457763672,
        fontSize: 14.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
