import 'package:flutter/material.dart';
import 'package:flutterapp/domain/flat_repository/src/models/feature_model.dart';
import 'package:flutterapp/screens/features_list_screen/widgets/features_list_item_container.dart';
import 'package:flutterapp/screens/features_list_screen/widgets/features_list_text.dart';

/* Group wifi
    Autogenerated by FlutLab FTF Generator
  */
class FeaturesListItem extends StatelessWidget {
  final FeatureModel featureModel;

  const FeaturesListItem({Key? key, required this.featureModel})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    if (featureModel.name.isEmpty) {
      return SizedBox(
        height: 67.0,
      );
    }
    return Container(
      height: 67.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Column(children: [
        SizedBox(
          width: 40.0,
          height: 40.0,
          child: FeaturesListItemContainer(
            child: featureModel.icon,
          ),
        ),
        SizedBox(
          height: 4.0,
        ),
        SizedBox(
          height: 23.0,
          child: FeaturesListText(text: featureModel.name),
        )
      ]),
    );
  }
}
