import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class FeaturesListGymIcon extends StatelessWidget {
  final bool isCreate;

  const FeaturesListGymIcon({super.key, this.isCreate = false});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 16.5,
      height: 16.5,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M9.70833 16.5L8.83333 15.625L11.7917 12.6667L3.83333 4.70833L0.875 7.66667L0 6.79167L1.16667 5.58333L0 4.41667L1.77083 2.64583L0.895833 1.77083L1.77083 0.895833L2.66667 1.75L4.41667 0L5.58333 1.16667L6.79167 0L7.66667 0.875L4.70833 3.83333L12.6667 11.7917L15.625 8.83333L16.5 9.70833L15.3333 10.9167L16.5 12.0833L14.7083 13.875L15.5833 14.75L14.7083 15.625L13.8333 14.75L12.0833 16.5L10.9167 15.3333L9.70833 16.5Z')
          ..color = const Color.fromARGB(255, 63, 141, 253),
      ]),
    );
  }
}
