import 'package:flutter/material.dart';

/* Text title
    Autogenerated by FlutLab FTF Generator
  */
class LoginTitle extends StatelessWidget {
  final String title;

  const LoginTitle({Key? key, required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        title,
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: const TextStyle(
          height: 1.152999997138977,
          fontSize: 16.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
