import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/user_provider/providers.dart';
import 'package:platonic/screens/settings_screen/widgets/widgets.dart';

/* Group logout_button
    Autogenerated by FlutLab FTF Generator
  */
class LogoutButton extends ConsumerWidget {
  const LogoutButton({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    Future<void> toggleLogoutButton() async {
      await ref.read(firebaseUserProvider.notifier).signOut();
      Navigator.pushNamedAndRemoveUntil(
          context, '/SplashScreen', (route) => false);
    }

    return GestureDetector(
      onTap: toggleLogoutButton,
      child: Container(
        height: 38.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: const Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 38.0,
                child: LogoutContainer(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 40.0,
                child: LogoutText(),
              )
            ]),
      ),
    );
  }
}
