import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:platonic/providers/meet_settings_provider/meet_settings_provider.dart';
import 'package:platonic/screens/dialog_screen/faculty_dialog_screen.dart';
import 'package:platonic/screens/dialog_screen/university_dialog_screen.dart';
import 'package:platonic/screens/settings_screen/widgets/widgets.dart';

/* Frame settings_form
    Autogenerated by FlutLab FTF Generator
  */
class SettingsForm extends ConsumerWidget {
  const SettingsForm({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final meetSettingsState = ref.watch(meetSettingsProvider);

    return SizedBox(
      height: 178.0,
      child: Column(children: [
        SizedBox(
          height: 25.0,
          child: StatusSwitch(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        const SizedBox(
          height: 32.0,
          child: SexToMeet(),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: SettingsSelect(
            placeholder: meetSettingsState.universityToMeet?.name ??
                'Your university to meet',
            title: '''University to meet''',
            settingsDialog: const UniversityDialogScreen(
              isMeetSettings: true,
            ),
          ),
        ),
        const SizedBox(
          height: 15.0,
        ),
        SizedBox(
          height: 38.0,
          child: SettingsSelect(
            placeholder: meetSettingsState.facultiesToMeet.isNotEmpty
                ? '${meetSettingsState.facultiesToMeet.first.facultyName} +${meetSettingsState.facultiesToMeet.length - 1}'
                : 'Your faculties to meet',
            title: '''Faculties to meet''',
            settingsDialog: const FacultyDialogScreen(
              isMeetSettings: true,
            ),
          ),
        )
      ]),
    );
  }
}
