import 'package:flutter/material.dart';
import 'package:platonic/screens/settings_screen/widgets/widgets.dart';

/* Group status_switch
    Autogenerated by FlutLab FTF Generator
  */
class StatusSwitch extends StatelessWidget {
  const StatusSwitch({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      height: 25.0,
      child: Row(children: [
        SizedBox(
          width: 116.0,
          child: SettingsTitle(
            title: '''Active''',
          ),
        ),
        SizedBox(
          width: 21.0,
        ),
        SwitchContainer(),
      ]),
    );
  }
}
