import 'package:flutter/material.dart';

/* Rectangle container
    Autogenerated by FlutLab FTF Generator
  */
class SwitchWhiteBackground extends StatelessWidget {
  const SwitchWhiteBackground({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 45.0,
      height: 25.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(30.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          color: const Color.fromARGB(255, 255, 255, 255),
        ),
      ),
    );
  }
}
