import 'package:flutter/material.dart';

/* Rectangle container
    Autogenerated by FlutLab FTF Generator
  */
class SwitchBlueBackground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 45.0,
      height: 25.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(30.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          color: Color.fromARGB(255, 63, 141, 253),
        ),
      ),
    );
  }
}
