import 'package:flutter/material.dart';
import 'package:platonic/helpers/svg/svg.dart';

/* Ellipse select
    Autogenerated by FlutLab FTF Generator
  */
class SwitchSelect extends StatelessWidget {
  const SwitchSelect({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 17.0,
      height: 17.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M17 8.5C17 13.1944 13.1944 17 8.5 17C3.80558 17 0 13.1944 0 8.5C0 3.80558 3.80558 0 8.5 0C13.1944 0 17 3.80558 17 8.5Z')
          ..color = const Color.fromARGB(255, 30, 30, 30),
      ]),
    );
  }
}
