import 'package:flutter/material.dart';
import 'package:platonic/widgets/start/Semicircle.dart';

/* Group background_decoration
    Autogenerated by FlutLab FTF Generator
  */
class BackgroundDecoration extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 390.0,
      height: 447.0042724609375,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 100.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 150.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 200.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 250.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 300.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            ),
            Positioned(
              left: 0.0,
              top: 350.0,
              right: null,
              bottom: null,
              width: 390.0,
              height: 97.0042724609375,
              child: Semicircle(),
            )
          ]),
    );
  }
}
