import 'package:flutter/material.dart';
import 'package:platonic/widgets/start/StartBottom.dart';
import 'package:platonic/widgets/start/StartMiddle.dart';
import 'package:platonic/widgets/start/StartTop.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class StartFrame extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 340.0,
      height: 510.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 170.0,
              child: StartTop(),
            ),
            Positioned(
              left: 0.0,
              top: 170.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 170.0,
              child: StartMiddle(),
            ),
            Positioned(
              left: 0.0,
              top: 340.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 170.0,
              child: StartBottom(),
            )
          ]),
    );
  }
}
