import 'package:flutterapp/domain/flat_repository/src/models/feature_model.dart';
import 'package:flutterapp/screens/features_screen/widgets/feature_item_container.dart';
import 'package:flutterapp/screens/create_flat_screen/step1_screen/widgets/navigate_before/navigate_before.dart';
import 'package:flutter/material.dart';

/* Frame features
    Autogenerated by FlutLab FTF Generator
  */
class FeaturesCreateScreen extends StatelessWidget {
  final List<FeatureModel> featuresModel = [
    FeatureModel(
      id: 1,
      name: 'Wi-Fi',
      icon: Icons.wifi,
    ),
    FeatureModel(
      id: 2,
      name: 'Air Conditioning',
      icon: Icons.ac_unit,
    ),
    FeatureModel(
      id: 3,
      name: 'Heating',
      icon: Icons.hvac,
    ),
    FeatureModel(
      id: 4,
      name: 'Closet',
      icon: Icons.checkroom,
    ),
    FeatureModel(
      id: 5,
      name: 'Dishwasher',
      icon: Icons.flatware,
    ),
    FeatureModel(
      id: 6,
      name: 'Microwave',
      icon: Icons.microwave,
    ),
    FeatureModel(
      id: 7,
      name: 'Oven',
      icon: Icons.fireplace,
    ),
    FeatureModel(
      id: 8,
      name: 'Refrigerator',
      icon: Icons.kitchen,
    ),
    FeatureModel(
      id: 9,
      name: 'Smoke',
      icon: Icons.smoke_free,
    ),
    FeatureModel(
      id: 10,
      name: 'Elevator',
      icon: Icons.elevator,
    ),
    FeatureModel(
      id: 11,
      name: 'Garage',
      icon: Icons.garage,
    ),
    FeatureModel(
      id: 12,
      name: 'Laundry',
      icon: Icons.local_laundry_service,
    ),
    FeatureModel(
      id: 13,
      name: 'Furnitures',
      icon: Icons.shelves,
    ),
    FeatureModel(
      id: 14,
      name: 'Gym',
      icon: Icons.fitness_center,
    ),
    FeatureModel(
      id: 15,
      name: 'Pool',
      icon: Icons.pool,
    ),
    FeatureModel(
      id: 16,
      name: 'Balcony',
      icon: Icons.balcony,
    ),
    FeatureModel(
      id: 17,
      name: 'Local Library',
      icon: Icons.local_library,
    ),
    FeatureModel(
      id: 18,
      name: 'Terrace',
      icon: Icons.deck,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Color.fromARGB(255, 27, 26, 29),
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child:
                Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              SizedBox(
                height: 25.0,
                child: NavigateBefore(
                  color: Color.fromARGB(255, 255, 255, 255),
                  title: 'Features',
                ),
              ),
              SizedBox(
                height: 22.0,
              ),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: List.generate(
                  (featuresModel.length / 2).ceil(),
                  (index) {
                    final start = index * 2;
                    final end = start + 2;
                    final features = featuresModel
                        .sublist(start, end)
                        .where((element) => element != null)
                        .toList();
                    return Container(
                      margin: EdgeInsets.only(
                          bottom: index == (featuresModel.length / 2).ceil() - 1
                              ? 0
                              : 10),
                      child: Row(
                        children: [
                          if (features.length > 0)
                            FeatureItemContainer(
                              featureModel: features[0],
                            ),
                          if (features.length > 1)
                            SizedBox(
                              width: 10.0,
                            ),
                          if (features.length > 1)
                            FeatureItemContainer(
                              featureModel: features[1],
                            ),
                        ],
                      ),
                    );
                  },
                ),
              ),
            ]),
          ),
        ));
  }
}
