import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter/material.dart';

/* Text bedroomtitle
    Autogenerated by FlutLab FTF Generator
  */
class FlatItemBedroomTitle extends StatelessWidget {
  final String bedroom;

  const FlatItemBedroomTitle({super.key, required this.bedroom});

  @override
  Widget build(BuildContext context) {
    return Text(
      AppLocalizations.of(context)!.flatHomeBedroom(bedroom),
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: const TextStyle(
        height: 1.3020000457763672,
        fontSize: 12.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 245, 245, 245),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
