import 'package:flutter/material.dart';
import 'package:flutterapp/screens/detail_screen/widgets/detail_cost_concept_ellipse.dart';
import 'package:flutterapp/screens/detail_screen/widgets/detail_monthly_cost/detail_cost_concept_title.dart';
import 'package:flutterapp/screens/detail_screen/widgets/detail_monthly_cost/detail_monthly_cost_subtitle.dart';

/* Group firstmonrh
    Autogenerated by FlutLab FTF Generator
  */
class DetailFirstMonth extends StatelessWidget {
  final int rentAdvance;

  const DetailFirstMonth({Key? key, required this.rentAdvance})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 20.0,
      child: Row(children: [
        Expanded(
          child: Row(
            children: [
              SizedBox(
                width: 5.0,
                height: 5.0,
                child: DetailCostConceptEllipse(
                  color: Color.fromARGB(255, 255, 0, 0),
                ),
              ),
              SizedBox(
                width: 10.0,
              ),
              SizedBox(
                height: 20.0,
                child: DetailCostConceptTitle(
                  title: '''First month rent advance''',
                ),
              ),
            ],
          ),
        ),
        SizedBox(
          width: 32.0,
        ),
        SizedBox(
          height: 23.0,
          child: DetailMonthlyCostSubtitle(
            cost: (rentAdvance / 100).toString(),
          ),
        ),
      ]),
    );
  }
}
