import 'package:flutter/material.dart';
import 'package:flutterapp/screens/detail_screen/widgets/detail_cost_concept_ellipse.dart';
import 'package:flutterapp/screens/detail_screen/widgets/detail_monthly_cost/detail_cost_concept_title.dart';
import 'package:flutterapp/screens/detail_screen/widgets/detail_monthly_cost/detail_monthly_cost_subtitle.dart';

/* Group costelectricity
    Autogenerated by FlutLab FTF Generator
  */
class DetailCostElectricity extends StatelessWidget {
  final int electricityCost;

  const DetailCostElectricity({Key? key, required this.electricityCost})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 18.0,
      child: Row(children: [
        Expanded(
          child: Row(
            children: [
              SizedBox(
                height: 5.0,
                child: DetailCostConceptEllipse(
                  color: Color.fromARGB(255, 249, 255, 0),
                ),
              ),
              SizedBox(
                width: 10.0,
              ),
              SizedBox(
                  height: 20.0,
                  child: DetailCostConceptTitle(
                    title: '''Cost of electricity, water, gas and internet''',
                  )),
            ],
          ),
        ),
        SizedBox(
          width: 32.0,
        ),
        SizedBox(
          height: 23.0,
          child: DetailMonthlyCostSubtitle(
            cost: (electricityCost / 100).toString(),
          ),
        ),
      ]),
    );
  }
}
