import 'package:flutter/material.dart';

/* Text First month rent advance
    Autogenerated by FlutLab FTF Generator
  */
class DetailCostConceptTitle extends StatelessWidget {
  final String title;

  const DetailCostConceptTitle({Key? key, required this.title})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Text(
      title,
      overflow: TextOverflow.ellipsis,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3020000457763672,
        fontSize: 14.0,
        fontFamily: 'DM Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
