import 'package:flutter/material.dart';

/* Text €100
    Autogenerated by FlutLab FTF Generator
  */
class DetailMonthlyCostSubtitle extends StatelessWidget {
  final String cost;

  const DetailMonthlyCostSubtitle({Key? key, required this.cost})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return RichText(
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        text: TextSpan(
          style: TextStyle(
            height: 1.3020000457763672,
            fontSize: 16.0,
            fontFamily: 'DM Sans',
            fontWeight: FontWeight.w400,
            color: Color.fromARGB(255, 130, 130, 132),

            /* letterSpacing: 0.0, */
          ),
          children: [
            TextSpan(
              text: '''€''',
              style: TextStyle(
                fontSize: 8.0,
                fontFamily: 'DM Sans',
                fontWeight: FontWeight.w500,
                color: Color.fromARGB(255, 130, 130, 132),

                /* letterSpacing: null, */
              ),
            ),
            TextSpan(
              text: cost,
              style: TextStyle(
                fontSize: 14.0,
                fontFamily: 'DM Sans',
                fontWeight: FontWeight.w500,
                color: Color.fromARGB(255, 130, 130, 132),

                /* letterSpacing: null, */
              ),
            )
          ],
        ));
  }
}
