import 'package:platonic/screens/error_dialog/error_dialog/widgets/widgets.dart';
import 'package:flutter/material.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class ErrorDialog extends StatelessWidget {
  final String error;

  const ErrorDialog({super.key, required this.error});

  @override
  Widget build(BuildContext context) {
    void toggleRetry() {
      Navigator.of(context).pop();
    }

    return Center(
      child: SingleChildScrollView(
        child: SizedBox(
          height: 146.0,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 53.0),
            child: Material(
              borderRadius: BorderRadius.circular(10.0),
              color: const Color.fromARGB(255, 217, 217, 217),
              child: Column(
                children: [
                  Expanded(
                    child: Container(
                      alignment: Alignment.center,
                      padding: const EdgeInsets.all(10.0),
                      child: ErrorText(error: error),
                    ),
                  ),
                  GestureDetector(
                    onTap: toggleRetry,
                    child: Container(
                      alignment: Alignment.center,
                      height: 36.0,
                      decoration: const BoxDecoration(
                          border: Border(
                              top: BorderSide(
                                  color: Color.fromARGB(255, 147, 147, 147),
                                  width: 0.5))),
                      child: const RetryText(),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
