import 'create_flat_detail_button_text.dart';
import 'package:flutter/material.dart';

/* Instance authentication_button
    Autogenerated by FlutLab FTF Generator
  */

class CreateFlatDetailButton extends StatelessWidget {
  final String text;

  const CreateFlatDetailButton({Key? key, required this.text})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      height: 44.0,
      decoration: BoxDecoration(
        color: const Color.fromARGB(255, 63, 141, 253),
        borderRadius: BorderRadius.circular(10.0),
        boxShadow: const [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: CreateFlatDetailButtonText(text: text),
    );
  }
}
