import 'package:flutter/material.dart';

/* Rectangle blue_container
    Autogenerated by FlutLab FTF Generator
  */
class BlueContainer extends StatelessWidget {
  const BlueContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 111.22222137451172,
      height: 29.217390060424805,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          color: const Color.fromARGB(255, 63, 141, 253),
        ),
      ),
    );
  }
}
