import 'package:flutter/material.dart';

/* Text man_option
    Autogenerated by FlutLab FTF Generator
  */
class ManOption extends StatelessWidget {
  const ManOption({super.key});

  @override
  Widget build(BuildContext context) {
    return const Align(
      alignment: Alignment.center,
      child: Text(
        '''Man''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.153000036875407,
          fontSize: 12.0,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
